// AUTO-GENERATED by tools/overlay_positions.py -- do not edit manually
namespace PadForge.Models2D;

public enum OverlayElementType { Button, Trigger, StickRing, StickClick, FaceButtonGroup, Touchpad }

public record OverlayElement(string ImageFile, string TargetName, OverlayElementType ElementType, double X, double Y, double Width, double Height);

public static class Xbox360Layout
{
    public const int BaseWidth = 1545;
    public const int BaseHeight = 955;
    public const string BasePath = "2DModels/XBOX360/XB360_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XB360_A_Button.png", "ButtonA", OverlayElementType.Button, 1178, 528, 127, 106),
        new("XB360_B_Button.png", "ButtonB", OverlayElementType.Button, 1312, 415, 122, 115),
        new("XB360_X_Button.png", "ButtonX", OverlayElementType.Button, 1058, 423, 126, 113),
        new("XB360_Y_Button.png", "ButtonY", OverlayElementType.Button, 1190, 314, 129, 118),
        new("XB360_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 138, 134, 312, 141),
        new("XB360_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 1125, 131, 285, 141),
        new("XB360_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 273, 26, 143, 152),
        new("XB360_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1160, 26, 143, 152),
        new("XB360_BackButton.png", "ButtonBack", OverlayElementType.Button, 546, 439, 92, 65),
        new("XB360_StartButton.png", "ButtonStart", OverlayElementType.Button, 914, 440, 92, 65),
        new("XB360_GuideButton.png", "ButtonGuide", OverlayElementType.Button, 689, 414, 171, 139),
        new("XB360_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 192, 439, 211, 185),
        new("XB360_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 892, 677, 211, 178),
        new("XB360_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 180, 434, 233, 195),
        new("XB360_RightStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 884, 662, 232, 191),
        new("XB360_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 484, 592, 108, 114),
        new("XB360_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 484, 729, 108, 114),
        new("XB360_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 383, 664, 134, 108),
        new("XB360_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 558, 664, 134, 107),
    };
}

public static class DS4Layout
{
    public const int BaseWidth = 1466;
    public const int BaseHeight = 783;
    public const string BasePath = "2DModels/DS4/DS4_V2_base.png";
    public const double StickMaxTravel = 25;

    public static readonly OverlayElement[] Overlays =
    {
        new("DS4_Face_Button.png", "ButtonA", OverlayElementType.Button, 1124, 445, 99, 90),
        new("DS4_Face_Button.png", "ButtonB", OverlayElementType.Button, 1230, 355, 99, 90),
        new("DS4_Face_Button.png", "ButtonX", OverlayElementType.Button, 1022, 354, 99, 90),
        new("DS4_Face_Button.png", "ButtonY", OverlayElementType.Button, 1124, 263, 99, 90),
        new("DS4_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 247, 278, 89, 97),
        new("DS4_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 247, 419, 89, 103),
        new("DS4_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 156, 358, 109, 85),
        new("DS4_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 319, 358, 109, 84),
        new("DS4_L1-Active.png", "LeftShoulder", OverlayElementType.Button, 190, 71, 199, 99),
        new("DS4_R1-Active.png", "RightShoulder", OverlayElementType.Button, 1076, 70, 199, 99),
        new("DS4_L2-Active.png", "LeftTrigger", OverlayElementType.Trigger, 231, 0, 134, 80),
        new("DS4_R2-Active.png", "RightTrigger", OverlayElementType.Trigger, 1102, 0, 133, 79),
        new("DS4_OptionsShare_Button.png", "ButtonBack", OverlayElementType.Button, 416, 214, 53, 85),
        new("DS4_OptionsShare_Button.png", "ButtonStart", OverlayElementType.Button, 996, 214, 53, 85),
        new("DS4_Home_Button.png", "ButtonGuide", OverlayElementType.Button, 688, 519, 87, 60),
        new("DS4_V2_LeftAnalogStick.png", "LeftThumbRing", OverlayElementType.StickRing, 427, 530, 165, 147),
        new("DS4_V2_RightAnalogStick.png", "RightThumbRing", OverlayElementType.StickRing, 874, 530, 165, 147),
        new("DS4_AnalogStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 411, 503, 196, 172),
        new("DS4_AnalogStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 859, 503, 196, 172),
    };
}

public static class DualSenseLayout
{
    public const int BaseWidth = 1467;
    public const int BaseHeight = 816;
    public const string BasePath = "2DModels/DualSense/DualSense_base.png";
    public const double StickMaxTravel = 25;

    public static readonly OverlayElement[] Overlays =
    {
        new("DualSense_Cross.png", "ButtonA", OverlayElementType.Button, 1162, 485, 81, 70),
        new("DualSense_Circle.png", "ButtonB", OverlayElementType.Button, 1276, 388, 80, 76),
        new("DualSense_Square.png", "ButtonX", OverlayElementType.Button, 1055, 394, 80, 72),
        new("DualSense_Triangle.png", "ButtonY", OverlayElementType.Button, 1168, 298, 81, 77),
        new("DualSense_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 214, 317, 91, 104),
        new("DualSense_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 216, 438, 91, 100),
        new("DualSense_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 130, 386, 113, 87),
        new("DualSense_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 278, 386, 114, 87),
        new("DualSense_L1-Active.png", "LeftShoulder", OverlayElementType.Button, 126, 107, 222, 131),
        new("DualSense_R1-Active.png", "RightShoulder", OverlayElementType.Button, 1121, 108, 222, 131),
        new("DualSense_L2-Active.png", "LeftTrigger", OverlayElementType.Trigger, 171, 1, 201, 152),
        new("DualSense_R2-Active.png", "RightTrigger", OverlayElementType.Trigger, 1096, 1, 201, 152),
        new("DualSense_Create_Button.png", "ButtonBack", OverlayElementType.Button, 349, 237, 55, 74),
        new("DualSense_Option_Button.png", "ButtonStart", OverlayElementType.Button, 1064, 236, 55, 74),
        new("DualSense_Home_Button.png", "ButtonGuide", OverlayElementType.Button, 688, 546, 98, 54),
        new("DualSense_LeftAnalogStick.png", "LeftThumbRing", OverlayElementType.StickRing, 410, 553, 175, 148),
        new("DualSense_RightAnalogStick.png", "RightThumbRing", OverlayElementType.StickRing, 883, 553, 175, 148),
        new("DualSense_AnalogStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 396, 528, 196, 170),
        new("DualSense_AnalogStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 875, 528, 196, 170),
        new("", "TouchpadClick", OverlayElementType.Button, 484, 181, 499, 35),
        new("", "Touchpad", OverlayElementType.Touchpad, 484, 220, 499, 220),
    };
}

public static class XboxOneSLayout
{
    public const int BaseWidth = 1543;
    public const int BaseHeight = 956;
    public const string BasePath = "2DModels/XBOXONE/XB1_S_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XB1_A_Button.png", "ButtonA", OverlayElementType.Button, 1160, 548, 86, 80),
        new("XB1_B_Button.png", "ButtonB", OverlayElementType.Button, 1284, 439, 86, 81),
        new("XB1_X_Button.png", "ButtonX", OverlayElementType.Button, 1047, 452, 90, 82),
        new("XB1_Y_Button.png", "ButtonY", OverlayElementType.Button, 1173, 346, 89, 83),
        new("XB1_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 137, 158, 272, 105),
        new("XB1_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 1132, 160, 274, 105),
        new("XB1_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 209, 8, 151, 139),
        new("XB1_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1182, 6, 153, 139),
        new("XB1_MenuButton.png", "ButtonStart", OverlayElementType.Button, 865, 468, 58, 54),
        new("XB1_ViewButton.png", "ButtonBack", OverlayElementType.Button, 618, 468, 58, 54),
        new("XB1_HomeButton.png", "ButtonGuide", OverlayElementType.Button, 723, 290, 95, 90),
        new("XB1_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 254, 422, 181, 180),
        new("XB1_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 892, 658, 186, 176),
        new("XB1_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 270, 442, 150, 141),
        new("XB1_LeftStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 910, 676, 150, 141),
        new("XB1_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 502, 614, 99, 100),
        new("XB1_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 502, 721, 97, 104),
        new("XB1_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 420, 675, 127, 89),
        new("XB1_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 557, 676, 124, 88),
    };
}

public static class XboxSeriesXLayout
{
    public const int BaseWidth = 1534;
    public const int BaseHeight = 954;
    public const string BasePath = "2DModels/XBOXSERIES/XBSeries_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XBSeries_A_Button.png", "ButtonA", OverlayElementType.Button, 1136, 475, 81, 78),
        new("XBSeries_B_Button.png", "ButtonB", OverlayElementType.Button, 1245, 367, 83, 79),
        new("XBSeries_X_Button.png", "ButtonX", OverlayElementType.Button, 1028, 378, 84, 80),
        new("XBSeries_Y_Button.png", "ButtonY", OverlayElementType.Button, 1138, 270, 87, 81),
        new("XBSeries_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 193, 91, 249, 86),
        new("XBSeries_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 1087, 88, 250, 85),
        new("XBSeries_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 238, 5, 122, 95),
        new("XBSeries_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1161, 3, 120, 84),
        new("XBSeries_MenuButton.png", "ButtonStart", OverlayElementType.Button, 856, 394, 57, 53),
        new("XBSeries_ViewButton.png", "ButtonBack", OverlayElementType.Button, 622, 394, 57, 53),
        new("XBSeries_HomeButton.png", "ButtonGuide", OverlayElementType.Button, 720, 222, 93, 88),
        new("XBSeries_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 264, 355, 177, 176),
        new("XBSeries_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 886, 586, 180, 170),
        new("XBSeries_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 279, 374, 147, 139),
        new("XBSeries_LeftStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 902, 602, 147, 139),
        new("XBSeries_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 503, 552, 110, 100),
        new("XBSeries_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 506, 664, 105, 105),
        new("XBSeries_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 430, 610, 126, 100),
        new("XBSeries_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 562, 611, 123, 98),
        new("XBSeries_ShareButton.png", "ButtonShare", OverlayElementType.Button, 732, 484, 68, 38),
    };
}
