// AUTO-GENERATED by tools/overlay_positions.py -- do not edit manually
namespace PadForge.Models2D;

public enum OverlayElementType { Button, Trigger, StickRing, StickClick, FaceButtonGroup, Touchpad }

public record OverlayElement(string ImageFile, string TargetName, OverlayElementType ElementType, double X, double Y, double Width, double Height);

public static class Xbox360Layout
{
    public const int BaseWidth = 1545;
    public const int BaseHeight = 955;
    public const string BasePath = "2DModels/XBOX360/XB360_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XB360_A_Button.png", "ButtonA", OverlayElementType.Button, 1178, 528, 127, 106),
        new("XB360_B_Button.png", "ButtonB", OverlayElementType.Button, 1312, 415, 122, 115),
        new("XB360_X_Button.png", "ButtonX", OverlayElementType.Button, 1058, 423, 126, 113),
        new("XB360_Y_Button.png", "ButtonY", OverlayElementType.Button, 1190, 314, 129, 118),
        new("XB360_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 138, 134, 312, 141),
        new("XB360_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 1125, 131, 285, 141),
        new("XB360_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 273, 26, 143, 152),
        new("XB360_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1160, 26, 143, 152),
        new("XB360_BackButton.png", "ButtonBack", OverlayElementType.Button, 546, 439, 92, 65),
        new("XB360_StartButton.png", "ButtonStart", OverlayElementType.Button, 914, 440, 92, 65),
        new("XB360_GuideButton.png", "ButtonGuide", OverlayElementType.Button, 689, 414, 171, 139),
        new("XB360_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 192, 439, 211, 185),
        new("XB360_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 892, 677, 211, 178),
        new("XB360_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 180, 434, 233, 195),
        new("XB360_RightStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 884, 662, 232, 191),
        new("XB360_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 484, 592, 108, 114),
        new("XB360_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 484, 729, 108, 114),
        new("XB360_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 383, 664, 134, 108),
        new("XB360_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 558, 664, 134, 107),
    };
}

public static class DS4Layout
{
    public const int BaseWidth = 1466;
    public const int BaseHeight = 783;
    public const string BasePath = "2DModels/DS4/DS4_V2_base.png";
    public const double StickMaxTravel = 25;

    public static readonly OverlayElement[] Overlays =
    {
        new("DS4_Face_Button.png", "ButtonA", OverlayElementType.Button, 1124, 445, 99, 90),
        new("DS4_Face_Button.png", "ButtonB", OverlayElementType.Button, 1230, 355, 99, 90),
        new("DS4_Face_Button.png", "ButtonX", OverlayElementType.Button, 1022, 354, 99, 90),
        new("DS4_Face_Button.png", "ButtonY", OverlayElementType.Button, 1124, 263, 99, 90),
        new("DS4_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 247, 278, 89, 97),
        new("DS4_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 247, 419, 89, 103),
        new("DS4_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 156, 358, 109, 85),
        new("DS4_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 319, 358, 109, 84),
        new("DS4_L1-Active.png", "LeftShoulder", OverlayElementType.Button, 190, 71, 199, 99),
        new("DS4_R1-Active.png", "RightShoulder", OverlayElementType.Button, 1076, 70, 199, 99),
        new("DS4_L2-Active.png", "LeftTrigger", OverlayElementType.Trigger, 231, 0, 134, 80),
        new("DS4_R2-Active.png", "RightTrigger", OverlayElementType.Trigger, 1102, 0, 133, 79),
        new("DS4_OptionsShare_Button.png", "ButtonBack", OverlayElementType.Button, 416, 214, 53, 85),
        new("DS4_OptionsShare_Button.png", "ButtonStart", OverlayElementType.Button, 996, 214, 53, 85),
        new("DS4_Home_Button.png", "ButtonGuide", OverlayElementType.Button, 688, 519, 87, 60),
        new("DS4_V2_LeftAnalogStick.png", "LeftThumbRing", OverlayElementType.StickRing, 427, 530, 165, 147),
        new("DS4_V2_RightAnalogStick.png", "RightThumbRing", OverlayElementType.StickRing, 874, 530, 165, 147),
        new("DS4_AnalogStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 411, 503, 196, 172),
        new("DS4_AnalogStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 859, 503, 196, 172),
    };
}

public static class DualSenseLayout
{
    public const int BaseWidth = 1467;
    public const int BaseHeight = 816;
    public const string BasePath = "2DModels/DualSense/DualSense_base.png";
    public const double StickMaxTravel = 25;

    public static readonly OverlayElement[] Overlays =
    {
        new("DualSense_Cross.png", "ButtonA", OverlayElementType.Button, 1154, 478, 97, 84),
        new("DualSense_Circle.png", "ButtonB", OverlayElementType.Button, 1268, 380, 98, 93),
        new("DualSense_Square.png", "ButtonX", OverlayElementType.Button, 1046, 386, 99, 89),
        new("DualSense_Triangle.png", "ButtonY", OverlayElementType.Button, 1159, 289, 100, 95),
        new("DualSense_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 217, 320, 86, 98),
        new("DualSense_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 218, 441, 86, 95),
        new("DualSense_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 135, 390, 104, 80),
        new("DualSense_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 282, 390, 105, 80),
        new("DualSense_L1-Active.png", "LeftShoulder", OverlayElementType.Button, 156, 85, 210, 124),
        new("DualSense_R1-Active.png", "RightShoulder", OverlayElementType.Button, 1100, 85, 210, 124),
        new("DualSense_L2-Active.png", "LeftTrigger", OverlayElementType.Trigger, 170, 1, 201, 152),
        new("DualSense_R2-Active.png", "RightTrigger", OverlayElementType.Trigger, 1098, 0, 197, 149),
        new("DualSense_Create_Button.png", "ButtonBack", OverlayElementType.Button, 353, 242, 47, 63),
        new("DualSense_Option_Button.png", "ButtonStart", OverlayElementType.Button, 1068, 242, 47, 63),
        new("DualSense_Home_Button.png", "ButtonGuide", OverlayElementType.Button, 690, 547, 93, 51),
        new("DualSense_LeftAnalogStick.png", "LeftThumbRing", OverlayElementType.StickRing, 406, 560, 175, 148),
        new("DualSense_RightAnalogStick.png", "RightThumbRing", OverlayElementType.StickRing, 888, 561, 175, 148),
        new("DualSense_AnalogStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 408, 560, 171, 148),
        new("DualSense_AnalogStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 890, 561, 171, 148),
        new("", "TouchpadClick", OverlayElementType.Button, 484, 181, 499, 35),
        new("", "Touchpad", OverlayElementType.Touchpad, 484, 220, 499, 220),
    };
}

public static class XboxOneSLayout
{
    public const int BaseWidth = 1543;
    public const int BaseHeight = 956;
    public const string BasePath = "2DModels/XBOXONE/XB1_S_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XB1_A_Button.png", "ButtonA", OverlayElementType.Button, 1145, 534, 115, 107),
        new("XB1_B_Button.png", "ButtonB", OverlayElementType.Button, 1270, 426, 114, 107),
        new("XB1_X_Button.png", "ButtonX", OverlayElementType.Button, 1032, 439, 119, 108),
        new("XB1_Y_Button.png", "ButtonY", OverlayElementType.Button, 1158, 333, 118, 110),
        new("XB1_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 161, 166, 312, 120),
        new("XB1_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 1072, 166, 312, 120),
        new("XB1_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 189, 2, 204, 188),
        new("XB1_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1150, 0, 208, 189),
        new("XB1_MenuButton.png", "ButtonStart", OverlayElementType.Button, 856, 460, 75, 70),
        new("XB1_ViewButton.png", "ButtonBack", OverlayElementType.Button, 610, 460, 75, 70),
        new("XB1_HomeButton.png", "ButtonGuide", OverlayElementType.Button, 708, 276, 124, 117),
        new("XB1_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 254, 422, 181, 180),
        new("XB1_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 892, 658, 186, 176),
        new("XB1_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 254, 427, 181, 170),
        new("XB1_LeftStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 892, 658, 186, 175),
        new("XB1_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 504, 624, 95, 96),
        new("XB1_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 506, 719, 90, 96),
        new("XB1_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 433, 678, 118, 83),
        new("XB1_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 551, 678, 118, 84),
    };
}

public static class XboxSeriesXLayout
{
    public const int BaseWidth = 1534;
    public const int BaseHeight = 954;
    public const string BasePath = "2DModels/XBOXSERIES/XBSeries_base.png";
    public const double StickMaxTravel = 30;

    public static readonly OverlayElement[] Overlays =
    {
        new("XBSeries_A_Button.png", "ButtonA", OverlayElementType.Button, 1122, 461, 109, 106),
        new("XBSeries_B_Button.png", "ButtonB", OverlayElementType.Button, 1230, 353, 112, 107),
        new("XBSeries_X_Button.png", "ButtonX", OverlayElementType.Button, 1013, 364, 114, 108),
        new("XBSeries_Y_Button.png", "ButtonY", OverlayElementType.Button, 1123, 256, 118, 110),
        new("XBSeries_LeftBumper_Active.png", "LeftShoulder", OverlayElementType.Button, 193, 59, 360, 124),
        new("XBSeries_RightBumper_Active.png", "RightShoulder", OverlayElementType.Button, 980, 60, 360, 123),
        new("XBSeries_LeftTrigger_Active.png", "LeftTrigger", OverlayElementType.Trigger, 222, 0, 166, 129),
        new("XBSeries_RightTrigger_Active.png", "RightTrigger", OverlayElementType.Trigger, 1134, 0, 164, 114),
        new("XBSeries_MenuButton.png", "ButtonStart", OverlayElementType.Button, 846, 385, 76, 70),
        new("XBSeries_ViewButton.png", "ButtonBack", OverlayElementType.Button, 612, 385, 76, 70),
        new("XBSeries_HomeButton.png", "ButtonGuide", OverlayElementType.Button, 701, 204, 132, 125),
        new("XBSeries_LeftStick.png", "LeftThumbRing", OverlayElementType.StickRing, 264, 355, 177, 176),
        new("XBSeries_RightStick.png", "RightThumbRing", OverlayElementType.StickRing, 886, 586, 180, 170),
        new("XBSeries_LeftStick_Click.png", "LeftThumbButton", OverlayElementType.StickClick, 264, 360, 177, 167),
        new("XBSeries_LeftStick_Click.png", "RightThumbButton", OverlayElementType.StickClick, 886, 586, 180, 170),
        new("XBSeries_D-PAD_Up.png", "DPadUp", OverlayElementType.Button, 520, 562, 76, 69),
        new("XBSeries_D-PAD_Down.png", "DPadDown", OverlayElementType.Button, 524, 689, 69, 69),
        new("XBSeries_D-PAD_Left.png", "DPadLeft", OverlayElementType.Button, 443, 628, 80, 63),
        new("XBSeries_D-PAD_Right.png", "DPadRight", OverlayElementType.Button, 593, 628, 80, 64),
        new("XBSeries_ShareButton.png", "ButtonShare", OverlayElementType.Button, 722, 479, 87, 49),
    };
}
