using System;

namespace PadForge.Engine.Common.AnalogKeyboard
{
    /// <summary>
    /// The Soup and AnalogSense families that answer requests instead of
    /// pushing reports, a pass at a time. A pass sends the family's requests,
    /// reads the answers and writes the complete key set into the output. The
    /// caller owns pacing and failure counting.
    /// </summary>
    public abstract class AnalogKeyboardPoller : AnalogKeyboardSession
    {
        public static AnalogKeyboardPoller Create(AnalogKeyboardProtocol protocol, ushort vendorId, ushort productId)
        {
            switch (protocol)
            {
                case AnalogKeyboardProtocol.DrunkDeer:
                    return new DrunkDeerPoller(productId);
                case AnalogKeyboardProtocol.Keychron:
                    var keychron = AnalogKeyboardCatalog.KeychronModel(vendorId, productId);
                    return keychron == null ? null : new KeychronPoller(keychron.Layout, keychron.FullPress, keychron.TravelMm);
                case AnalogKeyboardProtocol.Madlions:
                    var madlions = AnalogKeyboardCatalog.MadlionsLayout(productId);
                    return madlions == null ? null : new MadlionsPoller(madlions);
                case AnalogKeyboardProtocol.Bytech:
                    return new BytechPoller();
            }
            return null;
        }
    }

    /// <summary>The DrunkDeer models the identity answer names.</summary>
    public enum DrunkDeerModel
    {
        Unknown,
        A75Ansi,
        A75Pro,
        A75Iso,
        G60,
        G65,
        G75Ansi,
        G75Jis,
    }

    /// <summary>
    /// DrunkDeer: request report 4 <c>B6 03 01</c>, then three answers
    /// <c>04 B7</c> carrying their chunk number at byte 4 and 59 key bytes
    /// from byte 5, a 21-column grid scaled /40. Soup's getActiveKeysDrunkdeer
    /// and AnalogSense.js's AsProviderDrunkdeer, with HallJoy's checks
    /// (its UAP overlay, AnalogueKeyboard.cpp:817-853): every answer is 64
    /// bytes, starts <c>04 B7</c> and carries a chunk number below 3 that no
    /// earlier answer of the frame carried, and the grid is assembled in chunk
    /// order rather than arrival order.
    ///
    /// <para>Start asks the five products the identity table covers for
    /// their model with <c>04 A0 02</c>, HallJoy's
    /// halljoy_drunkdeer_identity.h, whose signatures come from DrunkDeer's
    /// Antler web driver. A model whose product matches reads the grid through
    /// its own map (drunkdeer.json, generated by HallJoy from Antler's layouts:
    /// the G60 has Esc where the A75 has the grave accent, the G65 keeps its
    /// navigation keys in column 14, the G75 moves the function row one cell
    /// left, the ISO and JIS boards carry their regional keys). Any other
    /// answer keeps the generic table Soup and AnalogSense.js read every
    /// DrunkDeer with, and the keyboard is read either way.</para>
    /// </summary>
    public sealed class DrunkDeerPoller : AnalogKeyboardPoller
    {
        public const int KeyBytesPerAnswer = 59;
        public const int AnswerLength = 64;
        private readonly byte[] _grid = new byte[KeyBytesPerAnswer * 3];
        private readonly ushort _productId;
        private DrunkDeerModel _model;
        private int[] _map;

        public DrunkDeerPoller(ushort productId = 0)
        {
            _productId = productId;
        }

        /// <summary>The model the identity answer named, once Start ran.</summary>
        public DrunkDeerModel Model => _model;

        public override string ModelName => ModelNameOf(_model);

        public override int[] KeyOrder => AnalogKeyboardData.KeysOf(_map ?? AnalogKeyboardData.Table("drunkdeer.json", "generic"));

        public static byte[] Request()
        {
            var r = new byte[64];
            r[0] = AnalogKeyboardCatalog.DrunkDeerReportId;
            r[1] = 0xB6;
            r[2] = 0x03;
            r[3] = 0x01;
            return r;
        }

        public static byte[] IdentityRequest()
        {
            var r = new byte[64];
            r[0] = AnalogKeyboardCatalog.DrunkDeerReportId;
            r[1] = 0xA0;
            r[2] = 0x02;
            return r;
        }

        /// <summary>The products HallJoy asks for their model.</summary>
        public static bool AsksIdentity(ushort productId)
            => productId is 0x2382 or 0x2383 or 0x2384 or 0x2386 or 0x2391;

        /// <summary>HallJoy's Parse: the answer is 64 bytes, starts
        /// <c>04 A0 02 00</c>, and bytes 5 to 7 are the model's signature.
        /// Anything else is <see cref="DrunkDeerModel.Unknown"/>.</summary>
        public static DrunkDeerModel ParseIdentity(ReadOnlySpan<byte> r)
        {
            if (r.Length != AnswerLength || r[0] != AnalogKeyboardCatalog.DrunkDeerReportId
                || r[1] != 0xA0 || r[2] != 0x02 || r[3] != 0x00)
                return DrunkDeerModel.Unknown;
            return (r[5], r[6], r[7]) switch
            {
                (11, 1, 1) or (11, 4, 1) => DrunkDeerModel.A75Ansi,
                (11, 4, 3) => DrunkDeerModel.A75Pro,
                (11, 4, 2) => DrunkDeerModel.A75Iso,
                (11, 3, 1) => DrunkDeerModel.G60,
                (11, 2, 1) or (15, 1, 1) => DrunkDeerModel.G65,
                (11, 4, 5) => DrunkDeerModel.G75Ansi,
                (11, 4, 7) => DrunkDeerModel.G75Jis,
                _ => DrunkDeerModel.Unknown,
            };
        }

        /// <summary>The product ID each model ships under. A model is taken
        /// only from a keyboard with that product ID.</summary>
        public static ushort ProductOf(DrunkDeerModel model) => model switch
        {
            DrunkDeerModel.A75Ansi or DrunkDeerModel.A75Pro or DrunkDeerModel.A75Iso => 0x2383,
            DrunkDeerModel.G65 => 0x2382,
            DrunkDeerModel.G60 => 0x2384,
            DrunkDeerModel.G75Ansi => 0x2386,
            DrunkDeerModel.G75Jis => 0x2391,
            _ => 0,
        };

        /// <summary>HallJoy's name for a model, null for an unknown one.</summary>
        public static string ModelNameOf(DrunkDeerModel model) => model switch
        {
            DrunkDeerModel.A75Ansi => "DrunkDeer A75 ANSI",
            DrunkDeerModel.A75Pro => "DrunkDeer A75 Pro",
            DrunkDeerModel.A75Iso => "DrunkDeer A75 ISO",
            DrunkDeerModel.G60 => "DrunkDeer G60 ANSI",
            DrunkDeerModel.G65 => "DrunkDeer G65 ANSI",
            DrunkDeerModel.G75Ansi => "DrunkDeer G75 ANSI",
            DrunkDeerModel.G75Jis => "DrunkDeer G75 JIS",
            _ => null,
        };

        /// <summary>The model's map in drunkdeer.json.</summary>
        public static string TableOf(DrunkDeerModel model) => model switch
        {
            DrunkDeerModel.A75Ansi => "a75_ansi",
            DrunkDeerModel.A75Pro => "a75_pro",
            DrunkDeerModel.A75Iso => "a75_iso",
            DrunkDeerModel.G60 => "g60",
            DrunkDeerModel.G65 => "g65",
            DrunkDeerModel.G75Ansi => "g75_ansi",
            DrunkDeerModel.G75Jis => "g75_jis",
            _ => "generic",
        };

        /// <summary>Asks for the model once, before the first pass, with one
        /// request and one answer, HallJoy's transactReport. A keyboard that
        /// does not answer, or names a model its product ID does not ship as,
        /// is read with the generic table.</summary>
        public override bool Start(IAnalogKeyboardTransport io)
        {
            if (!AsksIdentity(_productId)) return true;
            // HallJoy asks only under DrunkDeerMtx, taken within 100 ms, and
            // otherwise reads the keyboard with the generic table
            // (UniversalAnalogPluginFixed main.cpp:414-431).
            var mutex = AnalogKeyboardNamedMutex.Get(AnalogKeyboardNamedMutex.DrunkDeer);
            if (mutex != null && !mutex.Wait()) return true;
            try
            {
                return AskIdentity(io);
            }
            finally
            {
                mutex?.Release();
            }
        }

        private bool AskIdentity(IAnalogKeyboardTransport io)
        {
            io.DiscardStale();
            if (!io.Send(IdentityRequest())) return true;
            int n = io.Receive(Buffer, AnswerTimeoutMs);
            if (n < 0) return false;
            var model = n == 0 ? DrunkDeerModel.Unknown : ParseIdentity(Buffer.AsSpan(0, n));
            if (model != DrunkDeerModel.Unknown && ProductOf(model) == _productId)
            {
                _model = model;
                _map = AnalogKeyboardData.Table("drunkdeer.json", TableOf(model));
            }
            return true;
        }

        /// <summary>Copies one answer's key bytes into the grid. Returns the
        /// chunk number (0 to 2), or -1 when the report fails HallJoy's
        /// checks: not 64 bytes, not <c>04 B7</c>, a chunk number of 3 or
        /// more, or one <paramref name="seen"/> already holds.</summary>
        public static int ApplyAnswer(ReadOnlySpan<byte> raw, byte[] grid, int seen = 0)
        {
            if (raw.Length != AnswerLength || raw[0] != AnalogKeyboardCatalog.DrunkDeerReportId || raw[1] != 0xB7)
                return -1;
            int index = raw[4];
            if (index > 2 || (seen & (1 << index)) != 0) return -1;
            raw.Slice(5, KeyBytesPerAnswer).CopyTo(grid.AsSpan(index * KeyBytesPerAnswer, KeyBytesPerAnswer));
            return index;
        }

        /// <summary>Reads the grid through <paramref name="map"/>, the generic
        /// table when null. A byte is the key's travel in tenths of a
        /// millimeter, 40 at the bottom.</summary>
        public static void ParseGrid(ReadOnlySpan<byte> grid, AnalogKeyInputState output, int[] map = null)
        {
            map ??= AnalogKeyboardData.Table("drunkdeer.json", "generic");
            output.ResetForReuse();
            int n = Math.Min(grid.Length, map.Length);
            for (int i = 0; i < n; i++)
            {
                if (grid[i] == 0 || map[i] == 0) continue;
                output.Set(map[i], grid[i] / 40f);
            }
        }

        /// <summary>One pass under DrunkDeerMtx, as Soup takes it around
        /// the request and its three answers (AnalogueKeyboard.cpp:765-766).
        /// A pass that cannot take it in time is a quiet pass.</summary>
        public override AnalogPollResult Pass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            var mutex = AnalogKeyboardNamedMutex.Get(AnalogKeyboardNamedMutex.DrunkDeer);
            if (mutex != null && !mutex.Wait()) return AnalogPollResult.Idle;
            try
            {
                return LockedPass(io, output);
            }
            finally
            {
                mutex?.Release();
            }
        }

        private AnalogPollResult LockedPass(IAnalogKeyboardTransport io, AnalogKeyInputState output)
        {
            io.DiscardStale();
            if (!io.Send(Request())) return AnalogPollResult.Failed;
            Array.Clear(_grid);
            int seen = 0;
            for (int answer = 0; answer < 3; answer++)
            {
                int n = io.Receive(Buffer, AnswerTimeoutMs);
                if (n < 0) return AnalogPollResult.Failed;
                if (n == 0) return AnalogPollResult.NoAnswer;
                // HallJoy ends the device on a bad frame. A pass that fails
                // here counts as a miss instead, so one stray report from
                // another program on the same collection costs one pass, and
                // a keyboard that keeps failing still runs out of misses.
                int index = ApplyAnswer(Buffer.AsSpan(0, n), _grid, seen);
                if (index < 0) return AnalogPollResult.NoAnswer;
                seen |= 1 << index;
            }
            ParseGrid(_grid, output, _map);
            return AnalogPollResult.Ok;
        }
    }

    /// <summary>
    /// Keychron and Lemokey HE boards over the VIA raw HID channel. Start asks
    /// for the analog matrix version (<c>A9 01</c>), and a keyboard that does
    /// not answer with at least three bytes is not read, as in HallJoy's UAP
    /// overlay. A last byte of 0x45 marks AnalogSense's FAR firmware, which
    /// answers <c>A9 31</c> with every key's travel, 30 bytes per 32-byte
    /// answer, row-major, in <c>slots / 30 + 1</c> answers (its
    /// get_realtime_travel_all sends a report each time 30 bytes fill and
    /// then always one more). Stock firmware answers <c>A9 30 row col</c>
    /// one key at a time, so a pass reads the keys that are down or moving
    /// plus a rotating group of four, Soup's getActiveKeysKeychron pass
    /// order.
    ///
    /// <para>Where the stock answer carries the travel depends on the version,
    /// as Keychron's firmware writes it and its Launcher reads it (the
    /// Launcher's per-version readers, main.be11320b2a72b61b.js offsets
    /// 1700453, 1710613, 1721671, 1733365 and 1745815). Version 1 (the Q1 HE
    /// ANSI's first releases) holds 0 to 40 at byte 2, read over 40 whenever
    /// it is not 0, Soup's first reading (Soup b48da365). Version 2 holds the
    /// travel byte at byte 3 (analog_matrix.c:768-787 of hall_effect_playground
    /// a576a0b47b), versions 3 and 4 at byte 6 after the row and column echo
    /// (2025q3 analog_matrix.c:786-807), and on these a travel under 5 is
    /// rest and the full press less 5 is the bottom, Soup's 235 of 240.
    /// Version 5, the 8K boards' firmware, holds a little-endian u16 at bytes
    /// 5 and 6 after the echo, in the unit <c>A9 10</c> names in its byte 8
    /// (2 for 0.01 mm, 3 for 0.001 mm, else 0.1 mm). Its full scale is the
    /// axis maximum <c>A9 50</c> answers when the version answer's feature
    /// byte sets bit 0, else the Launcher's device-definition travel
    /// (getHeVersion and getAxisType, offsets 1752789 and 1750860). From
    /// version 3 on, an answer must echo the row and column it answers, as
    /// the Launcher checks.</para>
    ///
    /// <para>HallJoy reads its K6, Q2 and Q4 additions only on FAR firmware,
    /// a latency choice: its own stock test read correct values
    /// (docs/v1.4/VALIDATION_MATRIX.md:2309-2364). Here stock firmware is
    /// read on every board. Every stock image of these boards answers
    /// <c>A9 30</c> in one of the layouts above.</para>
    /// </summary>
    public sealed class KeychronPoller : AnalogKeyboardPoller
    {
        public const int AnswerDataLength = 32;
        public const int TravelBytesPerAnswer = 30;

        /// <summary>The travel byte at the bottom of a standard board's press
        /// (analog_matrix.h:26, 78).</summary>
        public const int StandardFullPress = 240;

        /// <summary>The Launcher's axis maximum when neither the board nor its
        /// definition names one (axis {min 0.2, max 3.8}).</summary>
        public const float DefaultTravelMm = 3.8f;

        /// <summary>Tries at a matching answer when the echo names another
        /// key, each within the answer timeout.</summary>
        private const int EchoTries = 4;

        private readonly AnalogKeyCodes.Layout _layout;
        private readonly int _fullPress;
        private readonly float _catalogTravelMm;
        private readonly ushort[] _travel;
        private int _amVersion = -1;
        private int _features;
        private bool _fullReports;
        private float _unitMm = 0.1f;
        private float _travelMm;
        private int _state = 1;

        /// <param name="fullPress">The travel byte at the bottom of a press.</param>
        /// <param name="travelMm">A version-5 board's travel when it does not
        /// report one, 0 for the Launcher's default.</param>
        public KeychronPoller(AnalogKeyCodes.Layout layout, int fullPress = StandardFullPress, float travelMm = 0f)
        {
            _layout = layout;
            _fullPress = fullPress > 5 ? fullPress : StandardFullPress;
            _catalogTravelMm = travelMm;
            _travel = new ushort[layout.Size];
        }

        /// <summary>The analog matrix version the board answered, -1 before.</summary>
        public int Version => _amVersion;

        /// <summary>A version-5 board's unit and full travel, in millimeters.</summary>
        public float UnitMm => _unitMm;
        public float TravelMm => _travelMm;

        /// <summary>True once the version answer said the firmware reports
        /// every key at once.</summary>
        public bool FullReports => _fullReports;

        public override int[] KeyOrder => AnalogKeyCodes.KeysOf(_layout);

        /// <summary>The answers one <c>A9 31</c> request brings for a matrix
        /// of <paramref name="slots"/> keys.</summary>
        public static int FullReportCount(int slots) => slots / TravelBytesPerAnswer + 1;

        public static byte[] Request(byte command, byte a = 0, byte b = 0)
        {
            var r = new byte[33];
            r[1] = 0xA9;
            r[2] = command;
            r[3] = a;
            r[4] = b;
            return r;
        }

        /// <summary>Depth for a Keychron travel byte: under 5 is rest, and
        /// the full press less 5 is the bottom (Soup's 235 of 240).</summary>
        public static float Depth(int travel, int fullPress = StandardFullPress)
            => travel >= 5 ? Math.Min(travel / (float)(fullPress - 5), 1f) : 0f;

        /// <summary>Depth for this board's travel as its version reports it.</summary>
        public float DepthOf(int travel)
        {
            if (_amVersion == 1) return travel > 0 ? Math.Min(travel / 40f, 1f) : 0f;
            if (_amVersion == 5)
            {
                float depth = travel * _unitMm / _travelMm;
                // The same rest band as the byte versions, 5 of 240.
                return depth >= 5f / StandardFullPress ? Math.Min(depth, 1f) : 0f;
            }
            return Depth(travel, _fullPress);
        }

        /// <summary>The version exchange under KeychronMtx, as Soup asks it
        /// inside its locked pass (AnalogueKeyboard.cpp:902-903). A Start
        /// that cannot take the mutex fails and is tried again.</summary>
        public override bool Start(IAnalogKeyboardTransport io)
        {
            var mutex = AnalogKeyboardNamedMutex.Get(AnalogKeyboardNamedMutex.Keychron);
            if (mutex != null && !mutex.Wait()) return false;
            try
            {
                return AskVersion(io) == AnalogPollResult.Ok
                    && (_amVersion != 5 || AskScale(io) == AnalogPollResult.Ok);
            }
            finally
            {
                mutex?.Release();
            }
        }

        /// <summary>A version-5 board's unit from <c>A9 10</c> (answer byte
        /// 8) and its axis maximum from <c>A9 50</c> (bytes 3 and 4 in that
        /// unit) when the version answer's feature bit 0 says it has one, as
        /// the Launcher reads them (getProfileInfo and getAxisType).</summary>
        private AnalogPollResult AskScale(IAnalogKeyboardTransport io)
        {
            io.DiscardStale();
            if (!io.Send(Request(0x10))) return AnalogPollResult.Failed;
            int off = ReceiveMatching(io, 0xA9, 0x10, out int len);
            if (off == -2) return AnalogPollResult.Failed;
            if (off < 0 || len < off + 9) return AnalogPollResult.NoAnswer;
            _unitMm = Buffer[off + 8] switch { 2 => 0.01f, 3 => 0.001f, _ => 0.1f };
            _travelMm = _catalogTravelMm > 0f ? _catalogTravelMm : DefaultTravelMm;
            if ((_features & 1) == 0) return AnalogPollResult.Ok;

            io.DiscardStale();
            if (!io.Send(Request(0x50))) return AnalogPollResult.Failed;
            off = ReceiveMatching(io, 0xA9, 0x50, out len);
            if (off == -2) return AnalogPollResult.Failed;
            if (off < 0 || len < off + 5) return AnalogPollResult.NoAnswer;
            float axis = ((Buffer[off + 4] << 8) | Buffer[off + 3]) * _unitMm;
            if (axis > 0f) _travelMm = axis;
            return AnalogPollResult.Ok;
        }

        /// <summary>The <c>A9 01</c> exchange: Ok with the version read,
        /// NoAnswer when no answer of at least three bytes came, Failed when
        /// the device is gone.</summary>
        private AnalogPollResult AskVersion(IAnalogKeyboardTransport io)
        {
            io.DiscardStale();
            if (!io.Send(Request(0x01))) return AnalogPollResult.Failed;
            int off = ReceiveMatching(io, 0xA9, 0x01, out int len);
            if (off == -2) return AnalogPollResult.Failed;
            if (off < 0 || len < off + 3) return AnalogPollResult.NoAnswer;
            _amVersion = Buffer[off + 2];
            _features = len > off + 4 ? Buffer[off + 4] : 0;
            _fullReports = Buffer[len - 1] == 0x45;
            return AnalogPollResult.Ok;
        }

        /// <summary>One pass under KeychronMtx (AnalogueKeyboard.cpp:902-903).
        /// A pass that cannot take it in time is a quiet pass.</summary>
        public override AnalogPollResult Pass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            var mutex = AnalogKeyboardNamedMutex.Get(AnalogKeyboardNamedMutex.Keychron);
            if (mutex != null && !mutex.Wait()) return AnalogPollResult.Idle;
            try
            {
                if (_amVersion < 0)
                {
                    var asked = AskVersion(io);
                    if (asked != AnalogPollResult.Ok) return asked;
                    if (_amVersion == 5 && (asked = AskScale(io)) != AnalogPollResult.Ok) return asked;
                }
                return _fullReports ? FullPass(io, output) : StockPass(io, output, isHeld);
            }
            finally
            {
                mutex?.Release();
            }
        }

        private AnalogPollResult FullPass(IAnalogKeyboardTransport io, AnalogKeyInputState output)
        {
            io.DiscardStale();
            if (!io.Send(Request(0x31))) return AnalogPollResult.Failed;
            int answers = FullReportCount(_travel.Length);
            for (int answer = 0; answer < answers; answer++)
            {
                int off = ReceiveMatching(io, 0xA9, 0x31, out int len);
                if (off == -2) return AnalogPollResult.Failed;
                // HallJoy takes an answer only at the full report length.
                if (off < 0 || len - off != AnswerDataLength) return AnalogPollResult.NoAnswer;
                for (int i = 0; i < TravelBytesPerAnswer; i++)
                {
                    int index = answer * TravelBytesPerAnswer + i;
                    if (index < _travel.Length) _travel[index] = Buffer[off + 2 + i];
                }
            }
            Publish(output);
            return AnalogPollResult.Ok;
        }

        /// <summary>The first data byte of the travel in a stock answer, by
        /// version: 2, 3, then 6, and 5 for version 5's u16.</summary>
        public static int TravelOffset(int version) => version switch
        {
            1 => 2,
            2 => 3,
            5 => 5,
            _ => version >= 3 ? 6 : 3,
        };

        private AnalogPollResult StockPass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            var keys = _layout.Keys;
            int valueAt = TravelOffset(_amVersion);
            bool wide = _amVersion == 5;
            bool echo = _amVersion >= 3;
            for (int i = 0; i < keys.Length; i++)
            {
                int code = keys[i];
                if (code == AnalogKeyCodes.None) continue;
                bool held = isHeld != null && isHeld(code);
                if (!held && _travel[i] == 0 && _state != (i >> 2) + 1) continue;
                byte row = (byte)(i / _layout.Columns), col = (byte)(i % _layout.Columns);
                io.DiscardStale();
                if (!io.Send(Request(0x30, row, col))) return AnalogPollResult.Failed;
                int off = -1, len = 0;
                for (int tries = 0; tries < EchoTries; tries++)
                {
                    off = ReceiveMatching(io, 0xA9, 0x30, out len);
                    if (off < 0 || !echo || len < off + 5
                        || (Buffer[off + 3] == row && Buffer[off + 4] == col)) break;
                    off = -1;
                }
                if (off == -2) return AnalogPollResult.Failed;
                // An answer too short to reach the travel fails the pass
                // (HallJoy's bounds check) instead of reading as rest.
                int last = valueAt + (wide ? 1 : 0);
                if (off < 0 || len <= off + last) return AnalogPollResult.NoAnswer;
                _travel[i] = wide
                    ? (ushort)(Buffer[off + valueAt] | (Buffer[off + valueAt + 1] << 8))
                    : Buffer[off + valueAt];
            }
            // Soup advances the rotation after every pass and wraps past the
            // last group.
            if (_state++ == (keys.Length >> 2) + 1) _state = 1;
            Publish(output);
            return AnalogPollResult.Ok;
        }

        private void Publish(AnalogKeyInputState output)
        {
            output.ResetForReuse();
            var keys = _layout.Keys;
            for (int i = 0; i < keys.Length; i++)
            {
                if (keys[i] == AnalogKeyCodes.None) continue;
                float depth = _fullReports ? Depth(_travel[i], _fullPress) : DepthOf(_travel[i]);
                if (depth > 0f) output.Set(keys[i], depth);
            }
        }
    }

    /// <summary>
    /// Madlions HE boards over the VIA raw HID channel: <c>02 96 1C</c> with
    /// the first key's offset at data byte 6 and a count of 4 at byte 7, and
    /// an answer carrying four keys of 5 bytes each after a 7-byte header, the
    /// travel a big-endian u16 at the end of each, 350 at the bottom. A pass
    /// reads the groups of four holding a key that is down or moving, plus a
    /// rotating block of sixteen keys, Soup's getActiveKeysMadlions pass order.
    ///
    /// <para>With HallJoy's fixes (its UAP overlay, AnalogueKeyboard.cpp:1250-1396):
    /// one answer per request, read after stale reports are dropped, an
    /// answer shorter than 27 data bytes (or none) zeroes that group and ends
    /// the pass, eight failures in a row of one group end the session, travel
    /// is clamped to 350, and the rotation wraps after ceil(keys / 16)
    /// blocks.</para>
    /// </summary>
    public sealed class MadlionsPoller : AnalogKeyboardPoller
    {
        public const int FullTravel = 350;
        public const int FailuresTolerated = 8;
        private readonly AnalogKeyCodes.Layout _layout;
        private readonly ushort[] _travel;
        private readonly int[] _failures;
        private int _state;

        public MadlionsPoller(AnalogKeyCodes.Layout layout)
        {
            _layout = layout;
            _travel = new ushort[layout.Size];
            _failures = new int[(layout.Size + 3) / 4];
        }

        public override int[] KeyOrder => AnalogKeyCodes.KeysOf(_layout);

        public static byte[] Request(int offset)
        {
            var r = new byte[33];
            r[1] = 0x02;
            r[2] = 0x96;
            r[3] = 0x1C;
            r[7] = (byte)offset;
            r[8] = 4;
            return r;
        }

        /// <summary>Reads the four travels out of an answer, clamped to
        /// <see cref="FullTravel"/>. False when the answer is shorter than the
        /// 7-byte header and four 5-byte records.</summary>
        public static bool ReadAnswer(ReadOnlySpan<byte> raw, Span<ushort> travel)
        {
            var data = AnalogKeyboardParsers.StripZeroReportId(raw);
            if (data.Length < 7 + 4 * 5) return false;
            for (int i = 0; i < 4; i++)
            {
                int at = 7 + i * 5 + 3;
                travel[i] = (ushort)Math.Min((data[at] << 8) | data[at + 1], FullTravel);
            }
            return true;
        }

        /// <summary>One pass under MadlionsMtx (<see cref="AnalogKeyboardNamedMutex"/>).
        /// A pass that cannot take it in time is a quiet pass: another reader
        /// is mid-exchange with the keyboard.</summary>
        public override AnalogPollResult Pass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            var mutex = AnalogKeyboardNamedMutex.Get(AnalogKeyboardNamedMutex.Madlions);
            if (mutex != null && !mutex.Wait()) return AnalogPollResult.Idle;
            try
            {
                return LockedPass(io, output, isHeld);
            }
            finally
            {
                mutex?.Release();
            }
        }

        /// <summary>
        /// A failed group ends the pass the way HallJoy's does
        /// (AnalogueKeyboard.cpp:1312-1347 of its overlay): its keys read 0,
        /// the keys collected before it are published and the ones after it
        /// are not, and only eight failures in a row of one group end the
        /// session. A write that fails counts as that group's failure, as
        /// HallJoy's transactReport returns nothing for it.
        /// </summary>
        private AnalogPollResult LockedPass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            var keys = _layout.Keys;
            Span<ushort> answer = stackalloc ushort[4];
            bool failed = false;
            int publishedKeys = keys.Length;
            for (int offset = 0; offset < keys.Length; offset += 4)
            {
                bool wanted = (offset >> 4) == _state;
                for (int i = 0; i < 4 && !wanted; i++)
                {
                    int index = offset + i;
                    if (index >= keys.Length || keys[index] == AnalogKeyCodes.None) continue;
                    if (_travel[index] != 0 || (isHeld != null && isHeld(keys[index]))) wanted = true;
                }
                if (!wanted) continue;

                io.DiscardStale();
                // A write that fails is this group's failure, unless the read
                // behind it shows the device gone.
                int n = io.Send(Request(offset))
                    ? io.Receive(Buffer, AnswerTimeoutMs)
                    : io.Receive(Buffer, 0) < 0 ? -1 : 0;
                if (n < 0) return AnalogPollResult.Failed;
                int group = offset >> 2;
                if (n == 0 || !ReadAnswer(Buffer.AsSpan(0, n), answer))
                {
                    for (int i = 0; i < 4 && offset + i < keys.Length; i++) _travel[offset + i] = 0;
                    failed = ++_failures[group] >= FailuresTolerated;
                    publishedKeys = offset;
                    break;
                }
                _failures[group] = 0;
                for (int i = 0; i < 4 && offset + i < keys.Length; i++) _travel[offset + i] = answer[i];
            }
            // HallJoy advances the rotation after a failed pass too.
            int blocks = (keys.Length + 15) / 16;
            if (blocks != 0 && ++_state >= blocks) _state = 0;
            if (failed) return AnalogPollResult.Failed;

            output.ResetForReuse();
            for (int i = 0; i < publishedKeys; i++)
                if (keys[i] != AnalogKeyCodes.None && _travel[i] != 0)
                    output.Set(keys[i], _travel[i] / (float)FullTravel);
            return AnalogPollResult.Ok;
        }
    }

    /// <summary>
    /// Bytech chips (Redragon K709 HE): report 9 carrying <c>97 00</c> and a
    /// checksum in its last byte, answered with <c>97 01</c>, a byte count at
    /// data byte 5 and 4-byte entries of big-endian position and distance, 355
    /// at the bottom and 10 or less at rest. AnalogSense.js's
    /// AsProviderBytech, the one reference. It re-asks after every answer and
    /// once a second besides, so a pass waits up to a second for its answer.
    /// </summary>
    public sealed class BytechPoller : AnalogKeyboardPoller
    {
        public const int PayloadLength = 63;
        public const int AnswerWaitMs = 1000;

        /// <summary>The request, report ID first: the payload's last byte is
        /// 255 minus the sum of the report ID and every other payload byte,
        /// modulo 256.</summary>
        public static byte[] Request()
        {
            var r = new byte[1 + PayloadLength];
            r[0] = AnalogKeyboardCatalog.BytechReportId;
            r[1] = 0x97;
            r[2] = 0x00;
            int sum = AnalogKeyboardCatalog.BytechReportId;
            for (int i = 1; i < r.Length - 1; i++) sum += r[i];
            r[r.Length - 1] = (byte)(255 - (sum % 256));
            return r;
        }

        /// <summary>Parses an answer into <paramref name="output"/>, replacing
        /// it. False when the report is not an answer.</summary>
        public static bool ParseAnswer(ReadOnlySpan<byte> raw, AnalogKeyInputState output)
        {
            // The answer's data starts with 97 01, after a report ID when the
            // collection numbers its reports.
            int off;
            if (raw.Length >= 2 && raw[0] == 0x97 && raw[1] == 0x01) off = 0;
            else if (raw.Length >= 3 && raw[1] == 0x97 && raw[2] == 0x01) off = 1;
            else return false;
            var data = raw.Slice(off);
            if (data.Length < 6) return false;
            int count = data[5];
            output.ResetForReuse();
            for (int i = 0; i < count; i += 4)
            {
                if (10 + i > data.Length) break;
                int position = (data[6 + i] << 8) | data[7 + i];
                int distance = (data[8 + i] << 8) | data[9 + i];
                int code = AnalogKeyCodes.BytechToCode(position);
                if (code != 0 && distance > 10) output.Set(code, Math.Min(distance / 355f, 1f));
            }
            return true;
        }

        public override AnalogPollResult Pass(IAnalogKeyboardTransport io, AnalogKeyInputState output,
            Func<int, bool> isHeld)
        {
            if (!io.Send(Request())) return AnalogPollResult.Failed;
            long deadline = Environment.TickCount64 + AnswerWaitMs;
            while (true)
            {
                int remaining = (int)(deadline - Environment.TickCount64);
                if (remaining <= 0) return AnalogPollResult.NoAnswer;
                int n = io.Receive(Buffer, remaining);
                if (n < 0) return AnalogPollResult.Failed;
                if (n == 0) return AnalogPollResult.NoAnswer;
                if (ParseAnswer(Buffer.AsSpan(0, n), output)) return AnalogPollResult.Ok;
            }
        }
    }
}
