// <auto-generated>
//     Generated from Strings.resx. Do not edit manually.
// </auto-generated>

using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Resources;

namespace PadForge.Resources.Strings;

public class Strings : INotifyPropertyChanged
{
    private static readonly ResourceManager _rm = new("PadForge.Resources.Strings.Strings", typeof(Strings).Assembly);

    public static Strings Instance { get; } = new();

    public static ResourceManager ResourceManager => _rm;

    public event PropertyChangedEventHandler PropertyChanged;

    // ── Weak CultureChanged event ──────────────────────────
    // Subscribers whose Target is null (static methods / static lambdas) are
    // stored with a strong reference.  Instance-method subscribers are stored
    // as (WeakReference<Target>, MethodInfo) so they don't prevent GC of the
    // subscribing object.  Dead entries are pruned on every raise.

    private static readonly object _cultureLock = new();
    private static readonly List<Action> _staticCultureHandlers = new();
    private static readonly List<WeakCultureEntry> _weakCultureHandlers = new();

    private readonly struct WeakCultureEntry
    {
        public readonly WeakReference<object> TargetRef;
        public readonly MethodInfo Method;
        public WeakCultureEntry(object target, MethodInfo method)
        {
            TargetRef = new WeakReference<object>(target);
            Method = method;
        }
    }

    /// <summary>
    /// Raised after <see cref="ChangeCulture"/> so ViewModels can refresh their own
    /// culture-dependent computed properties (status text, titles, etc.).
    /// Instance-method handlers are held weakly — subscribers do NOT need to
    /// unsubscribe to avoid leaking.
    /// </summary>
    public static event Action CultureChanged
    {
        add
        {
            if (value == null) return;
            lock (_cultureLock)
            {
                if (value.Target == null)
                    _staticCultureHandlers.Add(value);
                else
                    _weakCultureHandlers.Add(new WeakCultureEntry(value.Target, value.Method));
            }
        }
        remove
        {
            if (value == null) return;
            lock (_cultureLock)
            {
                if (value.Target == null)
                    _staticCultureHandlers.Remove(value);
                // Weak entries are auto-pruned on raise; explicit remove is best-effort.
            }
        }
    }

    private static void RaiseCultureChanged()
    {
        List<Action> snapshot;
        lock (_cultureLock)
        {
            snapshot = new List<Action>(_staticCultureHandlers.Count + _weakCultureHandlers.Count);
            snapshot.AddRange(_staticCultureHandlers);
            for (int i = _weakCultureHandlers.Count - 1; i >= 0; i--)
            {
                var entry = _weakCultureHandlers[i];
                if (entry.TargetRef.TryGetTarget(out var target))
                    snapshot.Add((Action)Delegate.CreateDelegate(typeof(Action), target, entry.Method));
                else
                    _weakCultureHandlers.RemoveAt(i);
            }
        }
        foreach (var handler in snapshot)
            handler();
    }

    public static string Get(string key) => _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>
    /// Changes the UI culture, refreshes all XAML bindings to this instance,
    /// and raises <see cref="CultureChanged"/> for ViewModel refresh.
    /// </summary>
    public static void ChangeCulture(CultureInfo culture)
    {
        Thread.CurrentThread.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        Instance.PropertyChanged?.Invoke(Instance, new PropertyChangedEventArgs(null));
        RaiseCultureChanged();
    }

    public string Common_Save => Get("Common_Save");
    public string Common_Cancel => Get("Common_Cancel");
    public string Common_Delete => Get("Common_Delete");
    public string Common_Add => Get("Common_Add");
    public string Common_Remove => Get("Common_Remove");
    public string Common_OK => Get("Common_OK");
    public string Common_Install => Get("Common_Install");
    public string Common_Uninstall => Get("Common_Uninstall");
    public string Common_Refresh => Get("Common_Refresh");
    public string Common_Copy => Get("Common_Copy");
    public string Common_Paste => Get("Common_Paste");
    public string Common_Enabled => Get("Common_Enabled");
    public string Common_Disabled => Get("Common_Disabled");
    public string Common_Installed => Get("Common_Installed");
    public string Common_NotInstalled => Get("Common_NotInstalled");
    public string Common_Ready => Get("Common_Ready");
    public string Common_Stopped => Get("Common_Stopped");
    public string Common_Running => Get("Common_Running");
    public string Server_RunningOn_Format => Get("Server_RunningOn_Format");
    public string Server_RunningClients_Format => Get("Server_RunningClients_Format");
    public string Server_ListeningOn_Format => Get("Server_ListeningOn_Format");
    public string Server_PortInUse_Format => Get("Server_PortInUse_Format");
    public string Server_AccessDenied_Format => Get("Server_AccessDenied_Format");
    public string Server_FailedToStart => Get("Server_FailedToStart");
    public string Common_Idle => Get("Common_Idle");
    public string Common_Online => Get("Common_Online");
    public string Common_Offline => Get("Common_Offline");
    public string Common_Unknown => Get("Common_Unknown");
    public string Common_Default => Get("Common_Default");
    public string Common_Browse => Get("Common_Browse");
    public string Common_Proceed => Get("Common_Proceed");
    public string Common_Stop => Get("Common_Stop");
    public string Common_Record => Get("Common_Record");
    public string Common_Recording => Get("Common_Recording");
    public string Common_Clear => Get("Common_Clear");
    public string Common_None => Get("Common_None");
    public string Common_Ms => Get("Common_Ms");
    public string Common_Unassigned => Get("Common_Unassigned");
    public string Common_PadForge => Get("Common_PadForge");
    public string ControllerType_Xbox360 => Get("ControllerType_Xbox360");
    public string ControllerType_DualShock4 => Get("ControllerType_DualShock4");
    public string ControllerType_DirectInput => Get("ControllerType_DirectInput");
    public string ControllerType_KeyboardMouse => Get("ControllerType_KeyboardMouse");
    public string ControllerType_MIDI => Get("ControllerType_MIDI");
    public string Main_ShuttingDown => Get("Main_ShuttingDown");
    public string Main_ReleasingControllers => Get("Main_ReleasingControllers");
    public string Main_PleaseWait => Get("Main_PleaseWait");
    public string Main_DevicesSuffix => Get("Main_DevicesSuffix");
    public string Main_AddController => Get("Main_AddController");
    public string Main_DeleteVC => Get("Main_DeleteVC");
    public string Main_FullScreen => Get("Main_FullScreen");
    public string Main_ShowPadForge => Get("Main_ShowPadForge");
    public string Main_VirtualController_Format => Get("Main_VirtualController_Format");
    public string Main_ViGEmNotInstalled => Get("Main_ViGEmNotInstalled");
    public string Main_EngineStopped => Get("Main_EngineStopped");
    public string Main_AwaitingControllers => Get("Main_AwaitingControllers");
    public string Main_Active => Get("Main_Active");
    public string Main_Initializing => Get("Main_Initializing");
    public string Main_DirectInputDriverNotInstalled => Get("Main_DirectInputDriverNotInstalled");
    public string Main_Xbox360_ViGEmNotInstalled => Get("Main_Xbox360_ViGEmNotInstalled");
    public string Main_Xbox360_Max_Format => Get("Main_Xbox360_Max_Format");
    public string Main_DS4_ViGEmNotInstalled => Get("Main_DS4_ViGEmNotInstalled");
    public string Main_DS4_Max_Format => Get("Main_DS4_Max_Format");
    public string Main_DI_DriverNotInstalled => Get("Main_DI_DriverNotInstalled");
    public string Main_DI_Max_Format => Get("Main_DI_Max_Format");
    public string Main_KBM_Max_Format => Get("Main_KBM_Max_Format");
    public string Main_MIDI_RequiresMidiServices => Get("Main_MIDI_RequiresMidiServices");
    public string Main_MIDI_Max_Format => Get("Main_MIDI_Max_Format");
    public string Status_InstallingViGEm => Get("Status_InstallingViGEm");
    public string Status_UninstallingViGEm => Get("Status_UninstallingViGEm");
    public string Status_InstallingHidHide => Get("Status_InstallingHidHide");
    public string Status_UninstallingHidHide => Get("Status_UninstallingHidHide");
    public string Status_InstallingVJoy => Get("Status_InstallingVJoy");
    public string Status_UninstallingVJoy => Get("Status_UninstallingVJoy");
    public string Status_DownloadingMidi => Get("Status_DownloadingMidi");
    public string Status_DownloadingInstallingMidi => Get("Status_DownloadingInstallingMidi");
    public string Status_UninstallingMidi => Get("Status_UninstallingMidi");
    public string Status_OperationCancelled => Get("Status_OperationCancelled");
    public string Status_MidiInstallFailed_Format => Get("Status_MidiInstallFailed_Format");
    public string Status_DeviceListRefreshed => Get("Status_DeviceListRefreshed");
    public string Status_Recorded_Format => Get("Status_Recorded_Format");
    public string Status_NowMap_Format => Get("Status_NowMap_Format");
    public string Status_MapPrompt_Format => Get("Status_MapPrompt_Format");
    public string Status_DirectionRight => Get("Status_DirectionRight");
    public string Status_DirectionDown => Get("Status_DirectionDown");
    public string Status_DirectionLeft => Get("Status_DirectionLeft");
    public string Status_DirectionUp => Get("Status_DirectionUp");
    public string Status_ViGEmDetectedRestarted => Get("Status_ViGEmDetectedRestarted");
    public string Status_VJoyDetectedRestarted => Get("Status_VJoyDetectedRestarted");
    public string Status_VJoyInstalledRestarted => Get("Status_VJoyInstalledRestarted");
    public string Status_VJoyRemovedRestarted => Get("Status_VJoyRemovedRestarted");
    public string Status_SDL3NotFound => Get("Status_SDL3NotFound");
    public string Status_SDL3NotFoundDetail => Get("Status_SDL3NotFoundDetail");
    public string Status_ViGEmNotDetected => Get("Status_ViGEmNotDetected");
    public string Status_ViGEmCheckFailed_Format => Get("Status_ViGEmCheckFailed_Format");
    public string Status_DriverOperationFailed_Format => Get("Status_DriverOperationFailed_Format");
    public string Status_SettingsCopied => Get("Status_SettingsCopied");
    public string Status_CopyFailed_Format => Get("Status_CopyFailed_Format");
    public string Status_InvalidClipboard => Get("Status_InvalidClipboard");
    public string Status_SettingsPasted => Get("Status_SettingsPasted");
    public string Status_PasteFailed_Format => Get("Status_PasteFailed_Format");
    public string Status_NoDeviceToCopyFrom => Get("Status_NoDeviceToCopyFrom");
    public string Status_NoOtherDevices => Get("Status_NoOtherDevices");
    public string Status_SettingsCopiedFromDevice => Get("Status_SettingsCopiedFromDevice");
    public string Status_ProfileCreatedEmpty_Format => Get("Status_ProfileCreatedEmpty_Format");
    public string Status_ProfileCreated_Format => Get("Status_ProfileCreated_Format");
    public string Status_ProfileDeleted_Format => Get("Status_ProfileDeleted_Format");
    public string Status_ProfileUpdated_Format => Get("Status_ProfileUpdated_Format");
    public string Status_ProfileLoaded_Format => Get("Status_ProfileLoaded_Format");
    public string Status_ProfileRevertedDefault => Get("Status_ProfileRevertedDefault");
    public string Status_VirtualController_Format => Get("Status_VirtualController_Format");
    public string Status_DeviceAssigned_Format => Get("Status_DeviceAssigned_Format");
    public string Status_Unmapped_Format => Get("Status_Unmapped_Format");
    public string Status_ErrorLoadingSettings_Format => Get("Status_ErrorLoadingSettings_Format");
    public string Status_SettingsSaved_Format => Get("Status_SettingsSaved_Format");
    public string Status_ErrorSavingSettings_Format => Get("Status_ErrorSavingSettings_Format");
    public string Status_SettingsResetDefaults => Get("Status_SettingsResetDefaults");
    public string Status_SettingsReloaded => Get("Status_SettingsReloaded");
    public string Status_NoSettingsFile => Get("Status_NoSettingsFile");
    public string Status_NoDeviceToRecord => Get("Status_NoDeviceToRecord");
    public string Status_RecordingPrompt_Format => Get("Status_RecordingPrompt_Format");
    public string Status_RecordingCancelled => Get("Status_RecordingCancelled");
    public string Status_RecordingTimedOut_Format => Get("Status_RecordingTimedOut_Format");
    public string Status_EngineStarted => Get("Status_EngineStarted");
    public string Status_EngineStopped => Get("Status_EngineStopped");
    public string Status_NoMapping => Get("Status_NoMapping");
    public string Status_Error_Format => Get("Status_Error_Format");
    public string Status_ProfileSwitched_Format => Get("Status_ProfileSwitched_Format");
    public string Status_ProfileSwitchedDefault => Get("Status_ProfileSwitchedDefault");
    public string Profile_Default => Get("Profile_Default");
    public string Status_NoDeviceSelected => Get("Status_NoDeviceSelected");
    public string Status_InvalidSlotIndex_Format => Get("Status_InvalidSlotIndex_Format");
    public string Status_FailedAssignDevice => Get("Status_FailedAssignDevice");
    public string Status_DeviceAssignedSlot_Format => Get("Status_DeviceAssignedSlot_Format");
    public string Status_DeviceUnassignedSlot_Format => Get("Status_DeviceUnassignedSlot_Format");
    public string Status_DeviceHidden => Get("Status_DeviceHidden");
    public string Status_DeviceRemoved => Get("Status_DeviceRemoved");
    public string Status_VCDeleted_Format => Get("Status_VCDeleted_Format");
    public string Dashboard_Title => Get("Dashboard_Title");
    public string Dashboard_InputEngine => Get("Dashboard_InputEngine");
    public string Dashboard_DevicesOnline => Get("Dashboard_DevicesOnline");
    public string Dashboard_VirtualControllers => Get("Dashboard_VirtualControllers");
    public string Dashboard_Mapped => Get("Dashboard_Mapped");
    public string Dashboard_Connected => Get("Dashboard_Connected");
    public string Dashboard_MotionServer => Get("Dashboard_MotionServer");
    public string Dashboard_DsuDescription => Get("Dashboard_DsuDescription");
    public string Dashboard_EnableDsu => Get("Dashboard_EnableDsu");
    public string Dashboard_Port => Get("Dashboard_Port");
    public string Dashboard_DsuFooter => Get("Dashboard_DsuFooter");
    public string Dashboard_WebController => Get("Dashboard_WebController");
    public string Dashboard_WebDescription => Get("Dashboard_WebDescription");
    public string Dashboard_EnableWeb => Get("Dashboard_EnableWeb");
    public string Dashboard_WebFooter => Get("Dashboard_WebFooter");
    public string Dashboard_Drivers => Get("Dashboard_Drivers");
    public string Dashboard_NoDevice => Get("Dashboard_NoDevice");
    public string Settings_Title => Get("Settings_Title");
    public string Settings_Appearance => Get("Settings_Appearance");
    public string Settings_AppearanceDesc => Get("Settings_AppearanceDesc");
    public string Settings_Theme => Get("Settings_Theme");
    public string Settings_ThemeSystem => Get("Settings_ThemeSystem");
    public string Settings_ThemeLight => Get("Settings_ThemeLight");
    public string Settings_ThemeDark => Get("Settings_ThemeDark");
    public string Settings_InputEngine => Get("Settings_InputEngine");
    public string Settings_InputEngineDesc => Get("Settings_InputEngineDesc");
    public string Settings_AutoStart => Get("Settings_AutoStart");
    public string Settings_BackgroundPolling => Get("Settings_BackgroundPolling");
    public string Settings_PollingInterval => Get("Settings_PollingInterval");
    public string Settings_HideDevices => Get("Settings_HideDevices");
    public string Settings_HideDevicesTooltip => Get("Settings_HideDevicesTooltip");
    public string Settings_Window => Get("Settings_Window");
    public string Settings_WindowDesc => Get("Settings_WindowDesc");
    public string Settings_MinimizeToTray => Get("Settings_MinimizeToTray");
    public string Settings_StartMinimized => Get("Settings_StartMinimized");
    public string Settings_StartAtLogin => Get("Settings_StartAtLogin");
    public string Settings_HidHide => Get("Settings_HidHide");
    public string Settings_HidHideDesc => Get("Settings_HidHideDesc");
    public string Settings_WhitelistedApps => Get("Settings_WhitelistedApps");
    public string Settings_WhitelistDesc => Get("Settings_WhitelistDesc");
    public string Settings_AddDots => Get("Settings_AddDots");
    public string Settings_ViGEmBus => Get("Settings_ViGEmBus");
    public string Settings_ViGEmDesc => Get("Settings_ViGEmDesc");
    public string Settings_VJoy => Get("Settings_VJoy");
    public string Settings_VJoyDesc => Get("Settings_VJoyDesc");
    public string Settings_MidiServices => Get("Settings_MidiServices");
    public string Settings_MidiDesc => Get("Settings_MidiDesc");
    public string Settings_MidiOsRequired => Get("Settings_MidiOsRequired");
    public string Settings_SettingsFile => Get("Settings_SettingsFile");
    public string Settings_SettingsFileDesc => Get("Settings_SettingsFileDesc");
    public string Settings_Reload => Get("Settings_Reload");
    public string Settings_ResetToDefaults => Get("Settings_ResetToDefaults");
    public string Settings_OpenFolder => Get("Settings_OpenFolder");
    public string Settings_UnsavedChanges => Get("Settings_UnsavedChanges");
    public string Settings_Diagnostics => Get("Settings_Diagnostics");
    public string Settings_DiagnosticsDesc => Get("Settings_DiagnosticsDesc");
    public string Settings_AppVersion => Get("Settings_AppVersion");
    public string Settings_DotNetRuntime => Get("Settings_DotNetRuntime");
    public string Settings_SdlVersion => Get("Settings_SdlVersion");
    public string Settings_Language => Get("Settings_Language");
    public string Settings_LanguageDesc => Get("Settings_LanguageDesc");
    public string About_Title => Get("About_Title");
    public string About_Subtitle => Get("About_Subtitle");
    public string About_Tagline => Get("About_Tagline");
    public string About_Description => Get("About_Description");
    public string About_BuiltWith => Get("About_BuiltWith");
    public string About_DotNet10 => Get("About_DotNet10");
    public string About_DotNet10Desc => Get("About_DotNet10Desc");
    public string About_SDL3 => Get("About_SDL3");
    public string About_SDL3Desc => Get("About_SDL3Desc");
    public string About_RawInput => Get("About_RawInput");
    public string About_RawInputDesc => Get("About_RawInputDesc");
    public string About_ViGEmBus => Get("About_ViGEmBus");
    public string About_ViGEmBusDesc => Get("About_ViGEmBusDesc");
    public string About_VJoy => Get("About_VJoy");
    public string About_VJoyDesc => Get("About_VJoyDesc");
    public string About_MidiServices => Get("About_MidiServices");
    public string About_MidiServicesDesc => Get("About_MidiServicesDesc");
    public string About_HelixToolkit => Get("About_HelixToolkit");
    public string About_HelixToolkitDesc => Get("About_HelixToolkitDesc");
    public string About_ModernWpf => Get("About_ModernWpf");
    public string About_ModernWpfDesc => Get("About_ModernWpfDesc");
    public string About_MvvmToolkit => Get("About_MvvmToolkit");
    public string About_MvvmToolkitDesc => Get("About_MvvmToolkitDesc");
    public string About_License => Get("About_License");
    public string About_LicenseText => Get("About_LicenseText");
    public string DeviceType_Gamepad => Get("DeviceType_Gamepad");
    public string DeviceType_Joystick => Get("DeviceType_Joystick");
    public string DeviceType_Wheel => Get("DeviceType_Wheel");
    public string DeviceType_FlightStick => Get("DeviceType_FlightStick");
    public string DeviceType_FirstPerson => Get("DeviceType_FirstPerson");
    public string DeviceType_Supplemental => Get("DeviceType_Supplemental");
    public string DeviceType_Mouse => Get("DeviceType_Mouse");
    public string DeviceType_Keyboard => Get("DeviceType_Keyboard");
    public string DeviceType_Touchpad => Get("DeviceType_Touchpad");
    public string DeviceType_Device => Get("DeviceType_Device");
    public string Devices_AllKeyboardsMerged => Get("Devices_AllKeyboardsMerged");
    public string Devices_AllMiceMerged => Get("Devices_AllMiceMerged");
    public string Devices_AllTouchpadsMerged => Get("Devices_AllTouchpadsMerged");
    public string Devices_Title => Get("Devices_Title");
    public string Devices_OnlineTotal => Get("Devices_OnlineTotal");
    public string Devices_Total => Get("Devices_Total");
    public string Devices_RemoveTooltip => Get("Devices_RemoveTooltip");
    public string Devices_Product => Get("Devices_Product");
    public string Devices_Type => Get("Devices_Type");
    public string Devices_GUID => Get("Devices_GUID");
    public string Devices_AppGUID => Get("Devices_AppGUID");
    public string Devices_SdlGUID => Get("Devices_SdlGUID");
    public string Devices_InstancePath => Get("Devices_InstancePath");
    public string Devices_VIDPID => Get("Devices_VIDPID");
    public string Devices_SubmitMapping => Get("Devices_SubmitMapping");
    public string Devices_VCAssignment => Get("Devices_VCAssignment");
    public string Devices_ToggleAssignment => Get("Devices_ToggleAssignment");
    public string Devices_InputMode => Get("Devices_InputMode");
    public string Devices_ForceRaw => Get("Devices_ForceRaw");
    public string Devices_ForceRawTooltip => Get("Devices_ForceRawTooltip");
    public string Devices_InputHiding => Get("Devices_InputHiding");
    public string Devices_HideFromGames => Get("Devices_HideFromGames");
    public string Devices_HideTooltip => Get("Devices_HideTooltip");
    public string Devices_HideTooltipInstall => Get("Devices_HideTooltipInstall");
    public string Devices_ConsumeMapped => Get("Devices_ConsumeMapped");
    public string Devices_ConsumeTooltip => Get("Devices_ConsumeTooltip");
    public string Devices_RawInputState => Get("Devices_RawInputState");
    public string Devices_Axes => Get("Devices_Axes");
    public string Devices_Buttons => Get("Devices_Buttons");
    public string Devices_Keyboard => Get("Devices_Keyboard");
    public string Devices_Mouse => Get("Devices_Mouse");
    public string Devices_DPadPOV => Get("Devices_DPadPOV");
    public string Devices_POV => Get("Devices_POV");
    public string Devices_Gyroscope => Get("Devices_Gyroscope");
    public string Devices_Accelerometer => Get("Devices_Accelerometer");
    public string Devices_Axis_Format => Get("Devices_Axis_Format");
    public string Devices_CapsSummary_Format => Get("Devices_CapsSummary_Format");
    public string Devices_Rumble => Get("Devices_Rumble");
    public string Devices_Gyro => Get("Devices_Gyro");
    public string Devices_Accel => Get("Devices_Accel");
    public string Devices_HideWarning_Format => Get("Devices_HideWarning_Format");
    public string Devices_HideAction => Get("Devices_HideAction");
    public string Devices_ConsumeAction => Get("Devices_ConsumeAction");
    public string Devices_WarnScope_Format => Get("Devices_WarnScope_Format");
    public string Devices_WarnHide_Format => Get("Devices_WarnHide_Format");
    public string Devices_WarnConsumeMouse => Get("Devices_WarnConsumeMouse");
    public string Devices_WarnConsumeKeyboard => Get("Devices_WarnConsumeKeyboard");
    public string Devices_WarnAction_Format => Get("Devices_WarnAction_Format");
    public string Devices_DeviceKind_Mouse => Get("Devices_DeviceKind_Mouse");
    public string Devices_DeviceKind_Keyboard => Get("Devices_DeviceKind_Keyboard");
    public string Pad_Macros => Get("Pad_Macros");
    public string Pad_Mappings => Get("Pad_Mappings");
    public string Pad_Sticks => Get("Pad_Sticks");
    public string Pad_Triggers => Get("Pad_Triggers");
    public string Pad_ForceFeedback => Get("Pad_ForceFeedback");
    public string Pad_Preset => Get("Pad_Preset");
    public string Pad_Custom => Get("Pad_Custom");
    public string Pad_VJoySticks => Get("Pad_VJoySticks");
    public string Pad_VJoyTriggers => Get("Pad_VJoyTriggers");
    public string Pad_VJoyPOVs => Get("Pad_VJoyPOVs");
    public string Pad_VJoyButtons => Get("Pad_VJoyButtons");
    public string Pad_MidiChannel => Get("Pad_MidiChannel");
    public string Pad_MidiChannelTooltip => Get("Pad_MidiChannelTooltip");
    public string Pad_MidiCCCount => Get("Pad_MidiCCCount");
    public string Pad_MidiCCCountTooltip => Get("Pad_MidiCCCountTooltip");
    public string Pad_MidiStartCC => Get("Pad_MidiStartCC");
    public string Pad_MidiStartCCTooltip => Get("Pad_MidiStartCCTooltip");
    public string Pad_MidiNoteCount => Get("Pad_MidiNoteCount");
    public string Pad_MidiNoteCountTooltip => Get("Pad_MidiNoteCountTooltip");
    public string Pad_MidiStartNote => Get("Pad_MidiStartNote");
    public string Pad_MidiStartNoteTooltip => Get("Pad_MidiStartNoteTooltip");
    public string Pad_MidiVelocity => Get("Pad_MidiVelocity");
    public string Pad_MidiVelocityTooltip => Get("Pad_MidiVelocityTooltip");
    public string Pad_SwitchTo2D => Get("Pad_SwitchTo2D");
    public string Pad_SwitchTo3D => Get("Pad_SwitchTo3D");
    public string Pad_TestLeftMotor => Get("Pad_TestLeftMotor");
    public string Pad_LeftMotor => Get("Pad_LeftMotor");
    public string Pad_TestRightMotor => Get("Pad_TestRightMotor");
    public string Pad_RightMotor => Get("Pad_RightMotor");
    public string Pad_MapAll => Get("Pad_MapAll");
    public string Pad_MapPrompt_Format => Get("Pad_MapPrompt_Format");
    public string Pad_MapAllTooltip => Get("Pad_MapAllTooltip");
    public string Pad_MapAllOneByOne => Get("Pad_MapAllOneByOne");
    public string Pad_MappingHint => Get("Pad_MappingHint");
    public string Pad_CopyTooltip => Get("Pad_CopyTooltip");
    public string Pad_PasteTooltip => Get("Pad_PasteTooltip");
    public string Pad_CopyFrom => Get("Pad_CopyFrom");
    public string Pad_CopyFromTooltip => Get("Pad_CopyFromTooltip");
    public string Pad_ResetAll => Get("Pad_ResetAll");
    public string Pad_ClearAll => Get("Pad_ClearAll");
    public string Pad_HeaderOutput => Get("Pad_HeaderOutput");
    public string Pad_HeaderSource => Get("Pad_HeaderSource");
    public string Pad_HeaderValue => Get("Pad_HeaderValue");
    public string Pad_HeaderOptions => Get("Pad_HeaderOptions");
    public string Pad_HeaderDeadZone => Get("Pad_HeaderDeadZone");
    public string Pad_Invert => Get("Pad_Invert");
    public string Pad_Half => Get("Pad_Half");
    public string Curve_Linear => Get("Curve_Linear");
    public string Curve_Smooth => Get("Curve_Smooth");
    public string Curve_Aggressive => Get("Curve_Aggressive");
    public string Curve_Instant => Get("Curve_Instant");
    public string Curve_SCurve => Get("Curve_SCurve");
    public string Curve_Delay => Get("Curve_Delay");
    public string Curve_Custom => Get("Curve_Custom");
    public string Pad_CalibrateCenter => Get("Pad_CalibrateCenter");
    public string Pad_Sampling => Get("Pad_Sampling");
    public string Pad_CenterOffsetX => Get("Pad_CenterOffsetX");
    public string Pad_CenterOffsetY => Get("Pad_CenterOffsetY");
    public string Pad_DeadZoneShape => Get("Pad_DeadZoneShape");
    public string Pad_DZScaledRadial => Get("Pad_DZScaledRadial");
    public string Pad_DZRadial => Get("Pad_DZRadial");
    public string Pad_DZAxial => Get("Pad_DZAxial");
    public string Pad_DZHybrid => Get("Pad_DZHybrid");
    public string Pad_DZSlopedScaledAxial => Get("Pad_DZSlopedScaledAxial");
    public string Pad_DZSlopedAxial => Get("Pad_DZSlopedAxial");
    public string Pad_MouseMovement => Get("Pad_MouseMovement");
    public string Pad_ScrollUp => Get("Pad_ScrollUp");
    public string Pad_ScrollDown => Get("Pad_ScrollDown");
    public string Pad_DeadZoneX => Get("Pad_DeadZoneX");
    public string Pad_DeadZoneY => Get("Pad_DeadZoneY");
    public string Pad_AntiDeadZoneX => Get("Pad_AntiDeadZoneX");
    public string Pad_AntiDeadZoneY => Get("Pad_AntiDeadZoneY");
    public string Pad_Linear => Get("Pad_Linear");
    public string Pad_SensitivityCurves => Get("Pad_SensitivityCurves");
    public string Pad_SensitivityCurveHint => Get("Pad_SensitivityCurveHint");
    public string Pad_SensitivityX => Get("Pad_SensitivityX");
    public string Pad_SensitivityY => Get("Pad_SensitivityY");
    public string Pad_MinRangeXLeft => Get("Pad_MinRangeXLeft");
    public string Pad_MaxRangeXRight => Get("Pad_MaxRangeXRight");
    public string Pad_MinRangeYDown => Get("Pad_MinRangeYDown");
    public string Pad_MaxRangeYUp => Get("Pad_MaxRangeYUp");
    public string Pad_XAxis => Get("Pad_XAxis");
    public string Pad_YAxis => Get("Pad_YAxis");
    public string Pad_Range => Get("Pad_Range");
    public string Pad_AntiDeadZone => Get("Pad_AntiDeadZone");
    public string Pad_SensitivityCurve => Get("Pad_SensitivityCurve");
    public string Pad_SensitivityCurveHintShort => Get("Pad_SensitivityCurveHintShort");
    public string Pad_Preset_Label => Get("Pad_Preset_Label");
    public string Pad_Live => Get("Pad_Live");
    public string Pad_TriggerAxis => Get("Pad_TriggerAxis");
    public string Pad_ForceFeedbackRumble => Get("Pad_ForceFeedbackRumble");
    public string Pad_OverallGain => Get("Pad_OverallGain");
    public string Pad_LeftMotorLabel => Get("Pad_LeftMotorLabel");
    public string Pad_RightMotorLabel => Get("Pad_RightMotorLabel");
    public string Pad_SwapMotors => Get("Pad_SwapMotors");
    public string Pad_TestRumble => Get("Pad_TestRumble");
    public string Pad_MotorActivity => Get("Pad_MotorActivity");
    public string Pad_ResetCenterOffsetX => Get("Pad_ResetCenterOffsetX");
    public string Pad_ResetCenterOffsetY => Get("Pad_ResetCenterOffsetY");
    public string Pad_ResetDeadZoneShape => Get("Pad_ResetDeadZoneShape");
    public string Pad_ResetDeadZoneX => Get("Pad_ResetDeadZoneX");
    public string Pad_ResetDeadZoneY => Get("Pad_ResetDeadZoneY");
    public string Pad_ResetAntiDeadZoneX => Get("Pad_ResetAntiDeadZoneX");
    public string Pad_ResetAntiDeadZoneY => Get("Pad_ResetAntiDeadZoneY");
    public string Pad_ResetLinear => Get("Pad_ResetLinear");
    public string Pad_ResetSensitivityX => Get("Pad_ResetSensitivityX");
    public string Pad_ResetSensitivityY => Get("Pad_ResetSensitivityY");
    public string Pad_ResetMinRangeX => Get("Pad_ResetMinRangeX");
    public string Pad_ResetMaxRangeX => Get("Pad_ResetMaxRangeX");
    public string Pad_ResetMinRangeY => Get("Pad_ResetMinRangeY");
    public string Pad_ResetMaxRangeY => Get("Pad_ResetMaxRangeY");
    public string Pad_ResetRange => Get("Pad_ResetRange");
    public string Pad_ResetAntiDeadZone => Get("Pad_ResetAntiDeadZone");
    public string Pad_ResetSensitivity => Get("Pad_ResetSensitivity");
    public string Pad_ResetOverallGain => Get("Pad_ResetOverallGain");
    public string Pad_ResetLeftMotor => Get("Pad_ResetLeftMotor");
    public string Pad_ResetRightMotor => Get("Pad_ResetRightMotor");
    public string Macro_RecordHint => Get("Macro_RecordHint");
    public string Macro_SysVolumeHint => Get("Macro_SysVolumeHint");
    public string Macro_AppVolumeHint => Get("Macro_AppVolumeHint");
    public string Macro_MouseMoveHint => Get("Macro_MouseMoveHint");
    public string Pad_ResetView => Get("Pad_ResetView");
    public string Macro_Name => Get("Macro_Name");
    public string Macro_Trigger => Get("Macro_Trigger");
    public string Macro_Fire => Get("Macro_Fire");
    public string Macro_OnPress => Get("Macro_OnPress");
    public string Macro_OnRelease => Get("Macro_OnRelease");
    public string Macro_WhileHeld => Get("Macro_WhileHeld");
    public string Macro_Always => Get("Macro_Always");
    public string Macro_Source => Get("Macro_Source");
    public string Macro_InputDevice => Get("Macro_InputDevice");
    public string Macro_OutputController => Get("Macro_OutputController");
    public string Macro_Threshold => Get("Macro_Threshold");
    public string Macro_ConsumeTrigger => Get("Macro_ConsumeTrigger");
    public string Macro_AlwaysDesc => Get("Macro_AlwaysDesc");
    public string Macro_ActionSequence => Get("Macro_ActionSequence");
    public string Macro_AddAction => Get("Macro_AddAction");
    public string Macro_EditAction => Get("Macro_EditAction");
    public string Macro_ActionType => Get("Macro_ActionType");
    public string Macro_ButtonPress => Get("Macro_ButtonPress");
    public string Macro_ButtonRelease => Get("Macro_ButtonRelease");
    public string Macro_KeyPress => Get("Macro_KeyPress");
    public string Macro_KeyRelease => Get("Macro_KeyRelease");
    public string Macro_Delay => Get("Macro_Delay");
    public string Macro_SetAxis => Get("Macro_SetAxis");
    public string Macro_SystemVolume => Get("Macro_SystemVolume");
    public string Macro_AppVolume => Get("Macro_AppVolume");
    public string Macro_MouseMove => Get("Macro_MouseMove");
    public string Macro_MouseButtonPress => Get("Macro_MouseButtonPress");
    public string Macro_MouseButtonRelease => Get("Macro_MouseButtonRelease");
    public string Macro_MouseScroll => Get("Macro_MouseScroll");
    public string Macro_Buttons => Get("Macro_Buttons");
    public string Macro_KeyCombo => Get("Macro_KeyCombo");
    public string Macro_KeyComboTooltip => Get("Macro_KeyComboTooltip");
    public string Macro_KeyComboHint => Get("Macro_KeyComboHint");
    public string Macro_Duration => Get("Macro_Duration");
    public string Macro_Axis => Get("Macro_Axis");
    public string Macro_LeftStickX => Get("Macro_LeftStickX");
    public string Macro_LeftStickY => Get("Macro_LeftStickY");
    public string Macro_RightStickX => Get("Macro_RightStickX");
    public string Macro_RightStickY => Get("Macro_RightStickY");
    public string Macro_LeftTrigger => Get("Macro_LeftTrigger");
    public string Macro_RightTrigger => Get("Macro_RightTrigger");
    public string Macro_AxisValue => Get("Macro_AxisValue");
    public string Macro_AxisFrom => Get("Macro_AxisFrom");
    public string Macro_SourceAxis => Get("Macro_SourceAxis");
    public string Macro_Device => Get("Macro_Device");
    public string Macro_VolumeLimit => Get("Macro_VolumeLimit");
    public string Macro_Process => Get("Macro_Process");
    public string Macro_ProcessTooltip => Get("Macro_ProcessTooltip");
    public string Macro_MouseLeft => Get("Macro_MouseLeft");
    public string Macro_MouseRight => Get("Macro_MouseRight");
    public string Macro_MouseMiddle => Get("Macro_MouseMiddle");
    public string Macro_MouseX1 => Get("Macro_MouseX1");
    public string Macro_MouseX2 => Get("Macro_MouseX2");
    public string Macro_Repeat => Get("Macro_Repeat");
    public string Macro_RepeatMode => Get("Macro_RepeatMode");
    public string Macro_Once => Get("Macro_Once");
    public string Macro_FixedCount => Get("Macro_FixedCount");
    public string Macro_UntilRelease => Get("Macro_UntilRelease");
    public string Macro_Count => Get("Macro_Count");
    public string Macro_DelayMs => Get("Macro_DelayMs");
    public string Macro_Sensitivity => Get("Macro_Sensitivity");
    public string Macro_NewMacro => Get("Macro_NewMacro");
    public string Macro_RecordTrigger => Get("Macro_RecordTrigger");
    public string Macro_NotSet => Get("Macro_NotSet");
    public string Macro_Btn_Format => Get("Macro_Btn_Format");
    public string Macro_None => Get("Macro_None");
    public string Macro_DeviceAxis_Format => Get("Macro_DeviceAxis_Format");
    public string Macro_UnknownAction => Get("Macro_UnknownAction");
    public string Macro_POV_Format => Get("Macro_POV_Format");
    public string Macro_Button_Format => Get("Macro_Button_Format");
    public string Macro_InvertAxis => Get("Macro_InvertAxis");
    public string Macro_ShowVolumeOsd => Get("Macro_ShowVolumeOsd");
    public string Macro_AxisDirection => Get("Macro_AxisDirection");
    public string Macro_AxisDirection_Any => Get("Macro_AxisDirection_Any");
    public string Macro_AxisDirection_Positive => Get("Macro_AxisDirection_Positive");
    public string Macro_AxisDirection_Negative => Get("Macro_AxisDirection_Negative");
    public string MacroAction_Press_Format => Get("MacroAction_Press_Format");
    public string MacroAction_Release_Format => Get("MacroAction_Release_Format");
    public string MacroAction_KeyPress_Format => Get("MacroAction_KeyPress_Format");
    public string MacroAction_KeyRelease_Format => Get("MacroAction_KeyRelease_Format");
    public string MacroAction_Wait_Format => Get("MacroAction_Wait_Format");
    public string MacroAction_SetAxis_Format => Get("MacroAction_SetAxis_Format");
    public string MacroAction_SysVol_Format => Get("MacroAction_SysVol_Format");
    public string MacroAction_SysVolLimit_Format => Get("MacroAction_SysVolLimit_Format");
    public string MacroAction_AppVol_Format => Get("MacroAction_AppVol_Format");
    public string MacroAction_AppVolLimit_Format => Get("MacroAction_AppVolLimit_Format");
    public string MacroAction_MouseMove_Format => Get("MacroAction_MouseMove_Format");
    public string MacroAction_MouseMoveLimit_Format => Get("MacroAction_MouseMoveLimit_Format");
    public string MacroAction_Scroll_Format => Get("MacroAction_Scroll_Format");
    public string MacroAction_ScrollLimit_Format => Get("MacroAction_ScrollLimit_Format");
    public string MacroAction_MousePress_Format => Get("MacroAction_MousePress_Format");
    public string MacroAction_MouseRelease_Format => Get("MacroAction_MouseRelease_Format");
    public string POV_Centered => Get("POV_Centered");
    public string POV_Up => Get("POV_Up");
    public string POV_UpRight => Get("POV_UpRight");
    public string POV_Right => Get("POV_Right");
    public string POV_DownRight => Get("POV_DownRight");
    public string POV_Down => Get("POV_Down");
    public string POV_DownLeft => Get("POV_DownLeft");
    public string POV_Left => Get("POV_Left");
    public string POV_UpLeft => Get("POV_UpLeft");
    public string Mapping_NotMapped => Get("Mapping_NotMapped");
    public string Mapping_Inv => Get("Mapping_Inv");
    public string Mapping_Half => Get("Mapping_Half");
    public string Mapping_InvHalf => Get("Mapping_InvHalf");
    public string Mapping_POV_Format => Get("Mapping_POV_Format");
    public string Mapping_NoDeviceMapped => Get("Mapping_NoDeviceMapped");
    public string Mapping_TouchpadX1 => Get("Mapping_TouchpadX1");
    public string Mapping_TouchpadY1 => Get("Mapping_TouchpadY1");
    public string Mapping_TouchpadX2 => Get("Mapping_TouchpadX2");
    public string Mapping_TouchpadY2 => Get("Mapping_TouchpadY2");
    public string Mapping_TouchpadContact1 => Get("Mapping_TouchpadContact1");
    public string Mapping_TouchpadContact2 => Get("Mapping_TouchpadContact2");
    public string Mapping_TouchpadClick => Get("Mapping_TouchpadClick");
    public string MappingCategory_Touchpad => Get("MappingCategory_Touchpad");
    public string DevObj_LeftStickX => Get("DevObj_LeftStickX");
    public string DevObj_LeftStickY => Get("DevObj_LeftStickY");
    public string DevObj_LeftTrigger => Get("DevObj_LeftTrigger");
    public string DevObj_RightStickX => Get("DevObj_RightStickX");
    public string DevObj_RightStickY => Get("DevObj_RightStickY");
    public string DevObj_RightTrigger => Get("DevObj_RightTrigger");
    public string DevObj_DPad => Get("DevObj_DPad");
    public string DevObj_Back => Get("DevObj_Back");
    public string DevObj_Start => Get("DevObj_Start");
    public string DevObj_Guide => Get("DevObj_Guide");
    public string DevObj_LeftShoulder => Get("DevObj_LeftShoulder");
    public string DevObj_RightShoulder => Get("DevObj_RightShoulder");
    public string DevObj_LeftStickButton => Get("DevObj_LeftStickButton");
    public string DevObj_RightStickButton => Get("DevObj_RightStickButton");
    public string DevObj_XAxis => Get("DevObj_XAxis");
    public string DevObj_YAxis => Get("DevObj_YAxis");
    public string DevObj_ZAxis => Get("DevObj_ZAxis");
    public string DevObj_XRotation => Get("DevObj_XRotation");
    public string DevObj_YRotation => Get("DevObj_YRotation");
    public string DevObj_ZRotation => Get("DevObj_ZRotation");
    public string DevObj_Slider => Get("DevObj_Slider");
    public string DevObj_POV => Get("DevObj_POV");
    public string DevObj_POVN => Get("DevObj_POVN");
    public string DevObj_Button => Get("DevObj_Button");
    public string DevObj_AxisN => Get("DevObj_AxisN");
    public string Profiles_Title => Get("Profiles_Title");
    public string Profiles_Management => Get("Profiles_Management");
    public string Profiles_Description => Get("Profiles_Description");
    public string Profiles_AutoSwitch => Get("Profiles_AutoSwitch");
    public string Profiles_ActiveProfile => Get("Profiles_ActiveProfile");
    public string Profiles_NoSlots => Get("Profiles_NoSlots");
    public string Profiles_New => Get("Profiles_New");
    public string Profiles_SaveAs => Get("Profiles_SaveAs");
    public string Profiles_Edit => Get("Profiles_Edit");
    public string Profiles_Load => Get("Profiles_Load");
    public string ProfileDialog_SaveAs => Get("ProfileDialog_SaveAs");
    public string ProfileDialog_Edit => Get("ProfileDialog_Edit");
    public string ProfileDialog_ProfileName => Get("ProfileDialog_ProfileName");
    public string ProfileDialog_DefaultName => Get("ProfileDialog_DefaultName");
    public string ProfileDialog_Executables => Get("ProfileDialog_Executables");
    public string CopyFrom_Title => Get("CopyFrom_Title");
    public string CopyFrom_SelectDevice => Get("CopyFrom_SelectDevice");
    public string FileDialog_SelectWhitelist => Get("FileDialog_SelectWhitelist");
    public string FileDialog_SelectGameExe => Get("FileDialog_SelectGameExe");
    public string FileDialog_ExeFilter => Get("FileDialog_ExeFilter");
    public string App_AlreadyRunning => Get("App_AlreadyRunning");
    public string App_FatalError => Get("App_FatalError");
    public string App_Error => Get("App_Error");
    public string App_UnexpectedError_Format => Get("App_UnexpectedError_Format");
    public string App_SuppressedErrors_Format => Get("App_SuppressedErrors_Format");
    public string Dashboard_PollingHz_Format => Get("Dashboard_PollingHz_Format");
    public string Dashboard_PollingDash => Get("Dashboard_PollingDash");
    public string Preview_CCOutputs => Get("Preview_CCOutputs");
    public string Preview_NoteOutputs => Get("Preview_NoteOutputs");
    public string Preview_Stick_Format => Get("Preview_Stick_Format");
    public string Preview_Trigger_Format => Get("Preview_Trigger_Format");
    public string Preview_DPad => Get("Preview_DPad");
    public string Preview_POV_Format => Get("Preview_POV_Format");
    public string Btn_LeftShoulder => Get("Btn_LeftShoulder");
    public string Btn_RightShoulder => Get("Btn_RightShoulder");
    public string Btn_Back => Get("Btn_Back");
    public string Btn_Start => Get("Btn_Start");
    public string Btn_Guide => Get("Btn_Guide");
    public string Btn_LeftStickButton => Get("Btn_LeftStickButton");
    public string Btn_RightStickButton => Get("Btn_RightStickButton");
    public string Btn_DPadUp => Get("Btn_DPadUp");
    public string Btn_DPadDown => Get("Btn_DPadDown");
    public string Btn_DPadLeft => Get("Btn_DPadLeft");
    public string Btn_DPadRight => Get("Btn_DPadRight");
    public string Btn_LeftTrigger => Get("Btn_LeftTrigger");
    public string Btn_RightTrigger => Get("Btn_RightTrigger");
    public string Stick_LeftThumbstick => Get("Stick_LeftThumbstick");
    public string Stick_RightThumbstick => Get("Stick_RightThumbstick");
    public string Stick_ScrollWheel => Get("Stick_ScrollWheel");
    public string Stick_Format => Get("Stick_Format");
    public string Trigger_Format => Get("Trigger_Format");
    public string Btn_LeftStickX => Get("Btn_LeftStickX");
    public string Btn_LeftStickY => Get("Btn_LeftStickY");
    public string Btn_RightStickX => Get("Btn_RightStickX");
    public string Btn_RightStickY => Get("Btn_RightStickY");
    public string Btn_Up => Get("Btn_Up");
    public string Btn_Down => Get("Btn_Down");
    public string Btn_Left => Get("Btn_Left");
    public string Btn_Right => Get("Btn_Right");
    public string Btn_Cross => Get("Btn_Cross");
    public string Btn_Circle => Get("Btn_Circle");
    public string Btn_Square => Get("Btn_Square");
    public string Btn_Triangle => Get("Btn_Triangle");
    public string Btn_L1 => Get("Btn_L1");
    public string Btn_R1 => Get("Btn_R1");
    public string Btn_L3 => Get("Btn_L3");
    public string Btn_R3 => Get("Btn_R3");
    public string Btn_Share => Get("Btn_Share");
    public string Btn_Options => Get("Btn_Options");
    public string Btn_PS => Get("Btn_PS");
    public string Btn_Touchpad => Get("Btn_Touchpad");
    // Mouse VK buttons
    public string Key_LButton => Get("Key_LButton");
    public string Key_RButton => Get("Key_RButton");
    public string Key_Cancel => Get("Key_Cancel");
    public string Key_MButton => Get("Key_MButton");
    public string Key_XButton1 => Get("Key_XButton1");
    public string Key_XButton2 => Get("Key_XButton2");
    // Common keys
    public string Key_Backspace => Get("Key_Backspace");
    public string Key_Tab => Get("Key_Tab");
    public string Key_Clear => Get("Key_Clear");
    public string Key_Enter => Get("Key_Enter");
    public string Key_Shift => Get("Key_Shift");
    public string Key_Control => Get("Key_Control");
    public string Key_Alt => Get("Key_Alt");
    public string Key_Pause => Get("Key_Pause");
    public string Key_CapsLock => Get("Key_CapsLock");
    public string Key_Escape => Get("Key_Escape");
    public string Key_Space => Get("Key_Space");
    // Navigation
    public string Key_PageUp => Get("Key_PageUp");
    public string Key_PageDown => Get("Key_PageDown");
    public string Key_End => Get("Key_End");
    public string Key_Home => Get("Key_Home");
    public string Key_Left => Get("Key_Left");
    public string Key_Up => Get("Key_Up");
    public string Key_Right => Get("Key_Right");
    public string Key_Down => Get("Key_Down");
    public string Key_Select => Get("Key_Select");
    public string Key_Print => Get("Key_Print");
    public string Key_Execute => Get("Key_Execute");
    public string Key_PrintScreen => Get("Key_PrintScreen");
    public string Key_Insert => Get("Key_Insert");
    public string Key_Delete => Get("Key_Delete");
    public string Key_Help => Get("Key_Help");
    // Windows keys
    public string Key_LWin => Get("Key_LWin");
    public string Key_RWin => Get("Key_RWin");
    public string Key_Apps => Get("Key_Apps");
    public string Key_Sleep => Get("Key_Sleep");
    // Numpad
    public string Key_Numpad => Get("Key_Numpad");
    public string Key_Separator => Get("Key_Separator");
    // Lock keys
    public string Key_NumLock => Get("Key_NumLock");
    public string Key_ScrollLock => Get("Key_ScrollLock");
    // Left/Right modifiers
    public string Key_LeftShift => Get("Key_LeftShift");
    public string Key_RightShift => Get("Key_RightShift");
    public string Key_LeftCtrl => Get("Key_LeftCtrl");
    public string Key_RightCtrl => Get("Key_RightCtrl");
    public string Key_LeftAlt => Get("Key_LeftAlt");
    public string Key_RightAlt => Get("Key_RightAlt");
    // Browser keys
    public string Key_BrowserBack => Get("Key_BrowserBack");
    public string Key_BrowserForward => Get("Key_BrowserForward");
    public string Key_BrowserRefresh => Get("Key_BrowserRefresh");
    public string Key_BrowserStop => Get("Key_BrowserStop");
    public string Key_BrowserSearch => Get("Key_BrowserSearch");
    public string Key_BrowserFavorites => Get("Key_BrowserFavorites");
    public string Key_BrowserHome => Get("Key_BrowserHome");
    // Media keys
    public string Key_VolumeMute => Get("Key_VolumeMute");
    public string Key_VolumeDown => Get("Key_VolumeDown");
    public string Key_VolumeUp => Get("Key_VolumeUp");
    public string Key_MediaNext => Get("Key_MediaNext");
    public string Key_MediaPrev => Get("Key_MediaPrev");
    public string Key_MediaStop => Get("Key_MediaStop");
    public string Key_MediaPlayPause => Get("Key_MediaPlayPause");
    public string Key_LaunchMail => Get("Key_LaunchMail");
    public string Key_LaunchMediaSelect => Get("Key_LaunchMediaSelect");
    public string Key_LaunchApp1 => Get("Key_LaunchApp1");
    public string Key_LaunchApp2 => Get("Key_LaunchApp2");
    // Numpad operators
    public string Key_NumpadMultiply => Get("Key_NumpadMultiply");
    public string Key_NumpadAdd => Get("Key_NumpadAdd");
    public string Key_NumpadSubtract => Get("Key_NumpadSubtract");
    public string Key_NumpadDecimal => Get("Key_NumpadDecimal");
    public string Key_NumpadDivide => Get("Key_NumpadDivide");
    // OEM keys
    public string Key_Semicolon => Get("Key_Semicolon");
    public string Key_Equals => Get("Key_Equals");
    public string Key_Comma => Get("Key_Comma");
    public string Key_Minus => Get("Key_Minus");
    public string Key_Period => Get("Key_Period");
    public string Key_Slash => Get("Key_Slash");
    public string Key_Grave => Get("Key_Grave");
    public string Key_LeftBracket => Get("Key_LeftBracket");
    public string Key_Backslash => Get("Key_Backslash");
    public string Key_RightBracket => Get("Key_RightBracket");
    public string Key_Apostrophe => Get("Key_Apostrophe");
    public string Mouse_LeftClick => Get("Mouse_LeftClick");
    public string Mouse_RightClick => Get("Mouse_RightClick");
    public string Mouse_MiddleClick => Get("Mouse_MiddleClick");
    public string Mouse_Button4 => Get("Mouse_Button4");
    public string Mouse_Button5 => Get("Mouse_Button5");
    public string Mouse_X => Get("Mouse_X");
    public string Mouse_Y => Get("Mouse_Y");
    public string Mouse_Scroll => Get("Mouse_Scroll");
    public string VJoy_Stick_Format => Get("VJoy_Stick_Format");
    public string VJoy_StickY_Format => Get("VJoy_StickY_Format");
    public string VJoy_Trigger_Format => Get("VJoy_Trigger_Format");
    public string VJoy_Button_Format => Get("VJoy_Button_Format");
    public string VJoy_DPad => Get("VJoy_DPad");
    public string VJoy_POV_Format => Get("VJoy_POV_Format");
    public string MacroAxis_XAxis => Get("MacroAxis_XAxis");
    public string MacroAxis_YAxis => Get("MacroAxis_YAxis");
    public string MacroAxis_XRotation => Get("MacroAxis_XRotation");
    public string MacroAxis_YRotation => Get("MacroAxis_YRotation");
    public string MacroAxis_ZAxis => Get("MacroAxis_ZAxis");
    public string MacroAxis_ZRotation => Get("MacroAxis_ZRotation");

    // Audio Bass Rumble
    public string Settings_AudioRumble => Get("Settings_AudioRumble");
    public string Settings_AudioRumbleDesc => Get("Settings_AudioRumbleDesc");
    public string Settings_AudioRumble_Enable => Get("Settings_AudioRumble_Enable");
    public string Settings_AudioRumble_Sensitivity => Get("Settings_AudioRumble_Sensitivity");
    public string Settings_AudioRumble_Cutoff => Get("Settings_AudioRumble_Cutoff");
    public string Settings_AudioRumble_LeftMotor => Get("Settings_AudioRumble_LeftMotor");
    public string Settings_AudioRumble_RightMotor => Get("Settings_AudioRumble_RightMotor");
    public string Settings_AudioRumble_Level => Get("Settings_AudioRumble_Level");

    // Audio Rumble Reset Tooltips
    public string Pad_ResetAudioSensitivity => Get("Pad_ResetAudioSensitivity");
    public string Pad_ResetAudioCutoff => Get("Pad_ResetAudioCutoff");
    public string Pad_ResetAudioLeftMotor => Get("Pad_ResetAudioLeftMotor");
    public string Pad_ResetAudioRightMotor => Get("Pad_ResetAudioRightMotor");
}
